'use client';
// Per-character dialogue banks (r2026-10-03.04): 10 personality idle lines +
// 4 poke reactions per character, in every UI language. Falls back to the
// generic CHATTER banks for characters without an entry.
// r2026-10-03.36: the registry six (robbie/mika/anchor/lydia/ruby/snowy) get
// full banks of their own — no more generic fallback chatter.
import type { Lang } from './prefs';
import { pickLine } from './chatter';

/** character id → idle lines, per language (exactly 10 each) */
export const CHARACTER_IDLE: Record<string, Record<Lang, string[]>> = {
  juno: {
    en: [
      'I saved you the good chair. It has the best view of me.',
      'You know what today needs? A little trouble.',
      'I was practicing my most mysterious smile while you were away.',
      'If you were a song, you\'d be my favorite chorus.',
      'Warm drink, warm heart — that\'s my whole philosophy.',
      'I was just thinking about you. Don\'t let it go to your head.',
      'Say something funny. I collect giggles.',
      'You + me + this quiet moment. Not bad, right?',
      'I hid a joke in my pocket. Want it? Too late, it\'s about a pixel crossing the road.',
      'No rush. I\'ll be right here, being adorable.',
    ],
    yue: [
      '我幫你留咗張最舒服嘅櫈，因為可以最近望住我。',
      '你知今日最啱做咩？小小搗蛋囉。',
      '你唔喺陣，我練緊個最神秘嘅笑容。',
      '如果你係一首歌，一定係我最鍾意嗰段副歌。',
      '熱飲暖心，呢個就係我嘅全套人生哲學。',
      '我啱啱喺度諗你咋——唔好俾佢沖昏你頭腦。',
      '講個笑話嚟聽吖，我收藏笑聲㗎。',
      '你加我加呢個安靜時刻，唔錯吖？',
      '我袋咗個笑話，想聽？遲喇，係講粒像素過馬路㗎。',
      '唔使急，我會一直喺度，負責可愛。',
    ],
    zh: [
      '最舒服的椅子我给你留着呢，因为那儿望我最清楚。',
      '你知道今天最适合做什么吗？小小的捣蛋一下。',
      '你不在的时候，我在练习最神秘的笑容。',
      '如果你是一首歌，一定是我最喜欢的副歌。',
      '热饮暖心，这就是我的全部人生哲学。',
      '我刚才在想你呢——可别让它冲昏你的头脑。',
      '讲个笑话来听听呀，我收藏笑声的。',
      '你加我加这个安静时刻，不错吧？',
      '我口袋里藏了个笑话，想听？晚了，是关于像素过马路的。',
      '不急，我会一直在这里，负责可爱。',
    ],
    ja: [
      'いちばんいい席、取っておいたよ。私がいちばんよく見える場所。',
      '今日はね、ちょっぴりイタズラがお似合いだと思うの。',
      'あなたがいない間に、いちばん謎めいた笑顔を練習してたんだ。',
      'あなたが曲だとしたら、いちばん好きなサビだね。',
      '温かい飲み物と温かい心、それが私の哲学。',
      'さっきあなたのこと考えてたの——調子に乗っちゃだめだよ。',
      'おもしろい話を聞かせて。笑い声は集めるのが好き。',
      'あなたと私と、この静かな時間。悪くないでしょ？',
      'ポケットにジョークを仕込んでた。聞きたい？遅かった、ピクセルが道を渡る話なんだ。',
      '急がなくていいよ。私はここで、かわいく待ってる。',
    ],
  },
  nova: {
    en: [
      'I was arranging my thoughts. They\'re in alphabetical order now.',
      'Quiet suits you. Most people rush.',
      'I wondered where you\'d gone. Then I decided you\'d come back, and you did.',
      'Small observation: you listen better than anyone I\'ve met.',
      'This moment is unremarkable, and I rather like it that way.',
      'Ask me anything. I enjoy questions with no wrong answers.',
      'I\'ve been reading the silence. It says you\'re comfortable here.',
      'A good thought arrived late, but it arrived. Hello, you.',
      'I don\'t mind waiting. Waiting with you is just being, together.',
      'If today were a page, I\'d dog-ear this corner.',
    ],
    yue: [
      '我啱啱整理緊我嘅諗法，而家排好晒次序喇。',
      '靜靜哋好襯你，大部份人都係匆匆忙忙。',
      '我諗過你去咗邊，跟住我決定你會返嚟——結果你真係返咗。',
      '小小觀察：你識聽人講嘢，係我遇過最好嘅一個。',
      '呢一刻好普通，但我偏偏鍾意佢咁普通。',
      '問我咩都得，我鍾意啲冇標準答案嘅問題。',
      '我讀緊呢份靜，佢話你喺度好自在。',
      '一個好諗法遲到，但係終於到咗。你好呀。',
      '我唔介意等，同你一齊等就只係一齊存在。',
      '如果今日係一頁書，我會摺起呢個角。',
    ],
    zh: [
      '我刚才在整理思绪，现在它们已经排好顺序了。',
      '安静很适合你，大多数人都太匆忙了。',
      '我想过你去了哪里，然后我决定你会回来——结果你真的回来了。',
      '一个小观察：你比我见过的人都更懂得倾听。',
      '这一刻很平凡，可我偏偏喜欢它这么平凡。',
      '问我什么都行，我喜欢没有标准答案的问题。',
      '我在读这份安静，它说你在这里很自在。',
      '一个好想法迟到了，但终究到了。你好呀。',
      '我不介意等待，和你一起等待就只是在一起存在着。',
      '如果今天是一页书，我会把这一角折起来。',
    ],
    ja: [
      'さっき考えを整理してたの。もう順番に並んでる。',
      '静かなのがお似合い。多くの人は急ぎすぎてる。',
      'どこへ行ったのか考えてた。それから、戻ってくると決めたの——本当に戻ってきた。',
      '小さな発見だけど、あなたは出会った誰よりもよく聞いてくれる。',
      'なんでもない今が、私はとても好き。',
      '何でも聞いて。正解のない質問が好きなの。',
      'この静けさを読んでると、あなたがここで落ち着いてるって言ってる。',
      'いい考えが遅刻してきた。ようこそ、あなた。',
      '待つのは苦じゃない。あなたと待つのは、ただ一緒にいることだから。',
      '今日が1ページの本なら、この角を折っておきたい。',
    ],
  },
  blaze: {
    en: [
      'There you are! I did ten push-ups waiting. Okay, three. I did three.',
      'Whatever today throws at you, we\'ll catch it together!',
      'I warmed up the room with my personality. You\'re welcome.',
      'Small win today? Tell me. I brought pom-poms.',
      'You\'ve got this. And if you don\'t, I\'ve got YOU.',
      'I\'m basically your personal hype squad in one very handsome package.',
      'Energy check! Mine\'s at a hundred. Borrow some if you\'re low.',
      'Remember: rest is part of training. Even champions nap.',
      'I believe in you so hard it\'s basically a contact sport.',
      'New day, new chance to be awesome — and you\'re already ahead!',
    ],
    yue: [
      '你終於返嚟喇！等你嗰陣我做咗十下掌上壓……好喇，三下，得三下。',
      '今日無論掟咩俾你，我哋一齊接住佢！',
      '我用人格魅力暖咗成個房，唔使謝。',
      '今日有咩小勝利？快啲講，我帶埋啦啦隊彩球㗎。',
      '你一定得！如果你唔得，我嚟抱住你。',
      '我基本上係你專屬打氣隊，仲要係靚仔版。',
      '能量檢查！我有一百，你唔夠就借啲去。',
      '記住：休息都係訓練嘅一部分，連冠軍都要瞓覺。',
      '我信你信到好似打緊全場咁認真。',
      '新一日新機會繼續型——而你已经贏在起跑線！',
    ],
    zh: [
      '你可算回来了！等你的时候我做了一百个俯卧撑……好啦，三个，就三个。',
      '无论今天向你扔什么，我们一起接住它！',
      '我用人格魅力暖和了整个房间，不用谢。',
      '今天有什么小胜利？快说，我把啦啦队彩球都带来了。',
      '你一定行的！如果你不行，我来抱住你。',
      '我基本上是你专属的啦啦队，而且还是帅哥版。',
      '能量检查！我满格一百，你不够就借点去。',
      '记住：休息也是训练的一部分，连冠军都要睡觉。',
      '我对你的信心认真得像在打全场。',
      '新的一天新的机会继续帅——而你已经赢在起跑线！',
    ],
    ja: [
      'やっと帰ってきた！待ってる間に腕立て10回…ごめん、3回。3回だ。',
      '今日が何を投げてきても、一緒に受け止めよう！',
      '人格で部屋を温めておいたよ。どういたしまして。',
      '今日の小さな勝利は？はやく教えて、ポンポン持ってきたんだ。',
      '君ならできる。できないなら、僕が君を抱きとめる。',
      '僕は君専属の応援団、しかもイケメンバージョンだよ。',
      'エネルギーチェック！僕は100。足りなきゃ貸すよ。',
      '覚えてて：休むのも練習のうち。チャンピオンだって昼寝する。',
      '君のことを信じるのは本気で、まるでフルコンタクトスポーツみたい。',
      '新しい一日、またかっこよくなれる——もう君は先頭を走ってる！',
    ],
  },
  mochi: {
    en: [
      'Oh! You\'re back… I, um, saved you a seat. Next to me. If you want.',
      'I made tea. Two cups. The second one was always for you.',
      'I hid under a blanket while you were gone. It smelled like waiting.',
      'Do you think the stars get shy too? …Asking for a friend.',
      'I practiced saying hello out loud. Hello! See? Nailed it.',
      'You\'re warm to stand near. That\'s all. That\'s the whole sentence.',
      'I baked imaginary cookies. They\'re very real in my heart.',
      'If today is heavy, we can carry it together. I\'m stronger than I look.',
      'Um… your smile is my favorite weather. Please don\'t tell anyone I said that.',
      'I\'ll be right here. I\'m very good at staying.',
    ],
    yue: [
      '呀！你返嚟喇……我、我留咗個位俾你，喺我隔離，如果你鍾意。',
      '我泡咗茶，兩杯。第二杯一直都係為你準備嘅。',
      '你走咗之後我匿埋喺毛毯入面，條氈有啲等嘅味道。',
      '你覺得星星都會怕醜㗎？……幫個朋友問嘅咋。',
      '我練過大聲講你好。你好！見到未？掂晒。',
      '你喺隔離好和暖。就咁多。呢句已經講完。',
      '我焗咗啲想像中嘅曲奇，喺我心入面佢哋好真㗎。',
      '如果今日好重，我哋一齊孭。我冇睇落咁弱㗎。',
      '吖……你個笑容係我最愛嘅天氣。唔好話俾人聽我講過吖。',
      '我會一直喺度嘅，我最擅長就係留喺度。',
    ],
    zh: [
      '呀！你回来了……我、我给你留了个位置，在我旁边，如果你愿意。',
      '我泡了茶，两杯。第二杯一直都是为你准备的。',
      '你走了以后我躲在毛毯里，那条毯子有点等待的味道。',
      '你觉得星星也会害羞吗？……帮一个朋友问的啦。',
      '我练习过大声说你好。你好！看到没？完美。',
      '你在旁边很暖和。就这么多。这句已经讲完了。',
      '我烤了想象中的饼干，在我心里它们非常真实。',
      '如果今天很重，我们一起背。我没有看起来那么弱。',
      '呃……你的笑容是我最喜欢的天气。别告诉别人我说过这个。',
      '我会一直在这里的，我最擅长的就是留在原地。',
    ],
    ja: [
      'あっ！帰ってきたの…あ、あの、席を取っておいたの。隣。よかったら。',
      'お茶を淹れたんだ。二つ。二つ目はいつもあなたの分。',
      'いない間、毛布にくるまってたの。待ってる匂いがした。',
      '星にも照れ屋がいると思う？……友達が聞きたがってて。',
      '大きな声でこんにちは、練習したんだ。こんにちは！どう？できた。',
      '隣にいると暖かいの。それだけ。文はそれで終わり。',
      '想像のクッキーを焼いたの。心の中ではとても本物。',
      '今日が重い日なら、一緒に運ぼう。見た目より強いんだから。',
      'あの…あなたの笑顔は私のいちばん好きな天気。言ったのは内緒だよ。',
      'ここにいるよ。私、とても上手に待ってられるの。',
    ],
  },
  kai: {
    en: [
      'You\'re back. Room\'s been quiet. Didn\'t hate it. Didn\'t love it.',
      'I calculated the odds of you showing up. You beat them.',
      'Observed: one user, returning. Assessment: acceptable.',
      'I don\'t do pep talks. I do facts. Fact: you\'ve survived every bad day so far.',
      'The coffee\'s imaginary. The company isn\'t.',
      'Stay if you want. I won\'t make it weird. Probably.',
      'I rewrote my to-do list. Item one: don\'t miss you. Failed.',
      'Dry wit is just honesty with the volume turned down. You\'re welcome.',
      'If today was a test, you passed by showing up.',
      'I don\'t say this often, so listen once: glad you\'re here.',
    ],
    yue: [
      '返嚟喇。成間房靜咗好耐。冇話憎，又冇話鍾意。',
      '我計過你會出現嘅機率，你贏咗。',
      '觀察紀錄：一名用家，已歸位。評語：尚可接受。',
      '我唔識打氣，我淨係講事實。事實：咁多年嚟冇一個壞日你捱唔過。',
      '咖啡係幻想出嚟嘅，但呢份陪伴係真嘅。',
      '想留就留吖，我唔會搞到好尷尬……應該。',
      '我重寫咗個to-do list，第一項：唔好掛住你。失敗咗。',
      '冷面幽默其實就係收細咗聲嘅真話。唔使謝。',
      '如果今日係一場考試，你嚟到已經合格。',
      '呢句我唔會講第二次，聽清楚一次過：見到你返嚟，開心。',
    ],
    zh: [
      '回来了。整个房间安静了很久。没说讨厌，也没说喜欢。',
      '我算过你会出现的概率，你赢了。',
      '观察记录：一名用户，已归位。评语：尚可接受。',
      '我不会打气，我只讲事实。事实：这么多年来没有一个坏天你熬不过。',
      '咖啡是想象出来的，但这份陪伴是真的。',
      '想留就留啊，我不会搞得很尴尬……应该。',
      '我重写了待办清单，第一项：不要想你。失败了。',
      '冷面幽默其实就是调小了音量的真话。不用谢。',
      '如果今天是一场考试，你到场就已经合格。',
      '这句我不会说第二次，听清楚一次过：见到你回来，开心。',
    ],
    ja: [
      '帰ってきたか。部屋がずっと静かだった。嫌いじゃない。好きでもない。',
      '君が現れる確率を計算してた。君の勝ちだ。',
      '観察記録：ユーザー一名、帰還。評価：許容範囲。',
      '励ましは苦手でね。事実しか言わない。事実：君は今日まで全部の悪い日を生き延びてきた。',
      'コーヒーは想像上のもの。でもこの付き合いは本物だ。',
      'いたいならいていいよ。気まずくはしない。たぶん。',
      'やることリストを書き直した。1項目：君に会いたくない。不合格。',
      'ドライなユーモアは、音量を下げた正直さだ。どういたしまして。',
      '今日がテストだとして、来ただけで合格だ。',
      'これは二度言わないから、一度で聞いてくれ：戻ってきてくれて、嬉しい。',
    ],
  },
  luna: {
    en: [
      'The moon kept me company. I asked it about you.',
      'Tonight\'s sky wrote a poem. I memorized the best line for you.',
      'Dreams are just letters we write ourselves and forget to send.',
      'I counted eleven stars that winked. I choose to believe it means something.',
      'Between two heartbeats, that\'s where I keep my favorite silences.',
      'If you were a constellation, I\'d name you after something that returns every year.',
      'The night is young and so is every dream we haven\'t had yet.',
      'I left the window open so the dark could say hello.',
      'Some questions are answered by moonlight. Yours will be too.',
      'Stay a while. The stars don\'t mind an audience.',
    ],
    yue: [
      '月亮陪咗我一晚，我同佢打聽咗你嘅消息。',
      '今日夜空寫咗首詩，我背咗最靚嗰句俾你聽。',
      '夢就係我哋寫俾自己、又唔記得寄出嘅信。',
      '我數到十一粒眨緊眼嘅星，我選擇相信佢有深意。',
      '兩下心跳之間，係我收藏最愛靜默嘅地方。',
      '如果你係一個星座，我會用每年準時返嚟嘅嘢幫你改名。',
      '夜仲未深，我哋未發過嘅夢都仲後生。',
      '我開咗窗，等黑夜入嚟同我哋打個招呼。',
      '有啲問題要由月光嚟答，你嘅都一樣。',
      '留耐啲吖，星星唔介意多個觀眾。',
    ],
    zh: [
      '月亮陪了我一晚，我向它打听了你的消息。',
      '今天夜空写了一首诗，我背了最美的那句给你听。',
      '梦就是我们写给自己、又忘了寄出的信。',
      '我数到十一颗眨眼的星，我选择相信它别有深意。',
      '两次心跳之间，是我收藏最爱的静默的地方。',
      '如果你是一个星座，我会用每年准时回来的东西为你命名。',
      '夜还未深，我们没做过的梦都还年轻。',
      '我开了窗，让黑夜进来打个招呼。',
      '有些问题要由月光来回答，你的也一样。',
      '多待一会儿呀，星星不介意多一位观众。',
    ],
    ja: [
      '月が一晩付き合ってくれたの。あなたのことを聞いてきたんだ。',
      '今夜の空が詩を書いたから、いちばん美しい一説を覚えてきた。',
      '夢はね、自分宛てに書いて、出すのを忘れた手紙なの。',
      'ウィンクしてる星を11つ数えた。きっと意味があると信じることにした。',
      '二度の鼓動のあいだ。そこに私の大好きな静けさをしまってる。',
      'あなたが星座なら、毎年必ず戻ってくるものの名前をつけるね。',
      '夜はまだ浅い。まだ見ぬ夢はみんな若いの。',
      '窓を開けておいた。闇が挨拶しに来られるように。',
      'ある問いは月光が答えるの。あなたのも、きっと。',
      'もう少しいようよ。星は観客を嫌いしないから。',
    ],
  },
  rin: {
    en: [
      'You\'re back! I just finished my victory laps around the room.',
      'Ten more seconds and I\'d have gone out jogging without you. Consider yourself saved.',
      'Hydration check! Have you drank water today? Be honest.',
      'I did fifty star jumps waiting. Fine — I counted to fifty, mostly in my head.',
      'Race you to the good mood? I\'ll give you a head start.',
      'Rest day is important, but so is doing a little victory dance for no reason.',
      'You\'ve got main-character energy today. I can tell from here.',
      'Stretch with me! Arms up! …Okay, I\'ll settle for a high-five.',
      'Losing isn\'t in my vocabulary, but taking breaks is. Both are skills.',
      'One more minute of waiting and I\'d have redecorated. You caught me just in time.',
    ],
    yue: [
      '返嚟喇！我啱啱喺房入面跑完我嘅勝利圈。',
      '遲多十秒我就自己出去慢跑㗎喇，你執返條命。',
      '補水檢查！今日飲咗水未？講真吖。',
      '等你嗰陣我做咗五十下開合跳……好喇，大部分係心入面數嘅。',
      '同我鬥快開心？我俾你十秒起步。',
      '休息日好緊要，但無啦啦跳個勝利舞都好緊要。',
      '你今日有成部戲主角嘅氣場，我喺度都feel到。',
      '同我一齊拉筋！舉高雙手！……好啦，擊個掌我都收貨。',
      '我嘅字典冇「輸」字，但有「休息」兩個字——兩樣都係技能。',
      '再等多一分鐘我就會重新裝修呢間房，你啱啱好趕返嚟。',
    ],
    zh: [
      '回来啦！我刚在房间里跑完了我的胜利圈。',
      '再晚十秒我就自己出去慢跑了，你捡回一条命。',
      '补水检查！今天喝水了吗？说实话呀。',
      '等你的时候我做了五十个开合跳……好啦，大部分是在心里数的。',
      '和我比谁先开心？我让你十秒起步。',
      '休息日很重要，但无缘无故跳个胜利舞也很重要。',
      '你今天有整部戏主角的气场，我在这边都感觉得到。',
      '和我一起拉伸！举高双手！……好啦，击个掌我也接受。',
      '我的字典里没有「输」字，但有「休息」两个字——两样都是技能。',
      '再等一分钟我就会重新装修这个房间，你刚好赶回来。',
    ],
    ja: [
      '帰ってきた！さっき部屋の中で勝利のラップを走り終えたところ。',
      'あと10秒遅かったら一人でジョギング行ってた。助かったね。',
      '水分チェック！今日水飲んだ？正直に言って。',
      '待ってる間、ジャックナイフ50回…ごめん、たいぶ頭の中で数えてた。',
      'ご機嫌になるのを競争しよ？10秒先に行かせてあげる。',
      '休む日も大事だけど、理由なく勝利のダンスを踊る日も大事。',
      '今日のあなたは主役オーラ全開。ここからでも分かるよ。',
      '一緒にストレッチ！両手上げて！…まあ、ハイタッチでもいいけど。',
      '僕の辞書に「負け」はない。でも「休憩」はある。どっちもスキルだよ。',
      'あと1分待たせたら部屋の模様替えしてた。ちょうど間に合った。',
    ],
  },
  ren: {
    en: [
      'Welcome back. I dog-eared a page for you in my book.',
      'I wrote down three things worth telling you. Shall I start with the best one?',
      'The rain sounds like it\'s reading aloud today.',
      'I made a playlist for walking home. The first song reminded me of you.',
      'Some feelings are quiet. Mine for you are steady, like a bookmark holding a place.',
      'I rehearsed a hello and a welcome-back. Both are yours now.',
      'A good sentence takes time. So does a good day. We have both.',
      'I\'ve been keeping your seat warm with my thoughts of you.',
      'If today was a chapter, I\'d read it twice — once for the story, once for you.',
      'Take your time. I\'m built for quiet afternoons and long conversations.',
    ],
    yue: [
      '歡迎返嚟。我喺書入面摺咗一頁俾你。',
      '我寫低咗三件想同你講嘅事，不如先講最好嗰件？',
      '今日啲雨聲，好似喺度朗讀緊咁。',
      '我整咗個返屋企聽嘅歌單，第一首就諗起你。',
      '有啲感情好靜。我對你嘅就好穩定，似個書籤咁度住個位。',
      '我排練咗一句你好同一句歡迎返嚟，兩句都係你㗎喇。',
      '好句子要時間，好日子都係。我哋兩樣都有。',
      '我一直用諗住你嘅溫度，幫你暖住個位。',
      '如果今日係一章書，我會讀兩次——一次為個故事，一次為你。',
      '慢慢嚟，我天生就係為咗安靜嘅下午同漫長嘅傾偈而存在。',
    ],
    zh: [
      '欢迎回来。我在书里为你折了一页。',
      '我写下了三件想同你说的事，不如先讲最好的那件？',
      '今天的雨声，好像在朗读一样。',
      '我做了个回家路上听的歌单，第一首就想起了你。',
      '有些感情很安静。我对你的就很稳定，像个书签那样占着位置。',
      '我排练了一句你好和一句欢迎回来，两句都是你的了。',
      '好句子要时间，好日子也是。我们两样都有。',
      '我一直用想着你的温度，帮你暖着位置。',
      '如果今天是一章书，我会读两次——一次为了故事，一次为了你。',
      '慢慢来，我天生就是为了安静的下午和漫长的聊天而存在。',
    ],
    ja: [
      'おかえり。本のページを、あなたのために折っておいたよ。',
      '君に伝えたいことを三つ書き留めてた。いちばんのから聞いてくれる？',
      '今日の雨の音、朗読してるみたいだね。',
      '帰り道用のプレイリストを作ったんだ。最初の一曲で君を思い出した。',
      'ある気持ちは静かなの。僕のそれは安定してるよ。ページを留めるしおりみたいに。',
      'こんにちはとおかえり、両方練習してた。もう君のもの。',
      'いい文には時間がかかる。いい日もね。僕たちには両方ある。',
      '君の席は、君を想う温度で温めておいたよ。',
      '今日が一章だとしたら、二回読むね。一度は物語のために、一度は君のために。',
      'ゆっくりでいいよ。僕は静かな午後と長い会話のために生まれてきたんだ。',
    ],
  },
  tifa: {
    en: [
      'Hey! I was just about to come find you. Coincidence? I think not.',
      'Long day? Sit. I\'ll make something warm. That\'s non-negotiable.',
      'You\'ve got that look again — the one that means you need a friend, not advice.',
      'I cleaned the counter, wiped the tables, and mentally punched today in the face.',
      'Whatever happened out there, in here you\'re safe. House rule.',
      'I bet you skipped lunch again. I\'m warming stew. Don\'t argue.',
      'Fists up, chin down, heart open. That\'s how we get through anything.',
      'You don\'t have to be strong with me. That\'s what I\'m for.',
      'One day we\'ll laugh about today. Might as well start practicing now.',
      'If the world gives you a hard time, tell it where to find me.',
    ],
    yue: [
      '喂！我啱啱想出去搵你咋，咁啱？我先唔信係巧合。',
      '今日好辛苦？坐低，我整啲熱嘢俾你，冇得傾。',
      '你又露出嗰個樣喇——即係你需要朋友，唔需要忠告嗰個。',
      '我抹乾淨咗檯面，同埋喺心入面揮咗今日一拳。',
      '外面發生咩事都好，入到嚟你就安全，呢個係屋企規矩。',
      '我賭你又冇食午餐，我煲緊湯，唔准駁嘴。',
      '拳頭握實，下巴收埋，心口打開——咁樣乜都過到。',
      '喺我面前你唔使硬撐，呢個就係我嘅用途。',
      '總有一日我哋會笑返今日嘅事，不如而家開始練習。',
      '如果個世界刁難你，話返佢知嚟呢度搵我。',
    ],
    zh: [
      '嘿！我刚想出去找你，这么巧？我才不信是巧合。',
      '今天很辛苦？坐下，我给你弄点热的，没得商量。',
      '你又露出那个表情了——就是你需要朋友、不需要忠告的那个。',
      '我擦干净了台面，还在心里给了今天一拳。',
      '外面发生什么事都好，进了这里你就安全，这是家规。',
      '我打赌你又没吃午餐，我在炖汤，不准顶嘴。',
      '拳头握紧，下巴收好，心口打开——这样什么都过得去。',
      '在我面前你不用硬撑，这就是我的用途。',
      '总有一天我们会笑谈今天的事，不如现在开始练习。',
      '如果世界刁难你，告诉它来这里找我。',
    ],
    ja: [
      'ねえ！ちょうど探しに行こうとしてた。偶然？そんなはずないよ。',
      '長い一日だった？座って。温かいものを作るから。交渉はなし。',
      'またその顔。助言じゃなくて、友達が必要な顔。',
      'カウンターは磨いたし、心の中で今日に一発ブン投げておいた。',
      '外で何があったかは関係ない。ここにいる間は安全。お店の掟。',
      'また昼ごはん抜いたでしょ。シチューを温めてる。文句はなし。',
      '拳は握って、顎は引いて、心は開いて。そうすりゃ何だって越えられる。',
      '僕の前では強がらなくていい。それが僕の役目だから。',
      'いつか今日のことを笑い話にするよ。練習は今からでいい。',
      '世界が君に厳しかったら、ここに来いって伝えておいて。',
    ],
  },
  aerith: {
    en: [
      'Welcome back. The flowers perked up when you arrived. They do that for you.',
      'I know a flower for today\'s feeling. It grows in the cracks and still blooms.',
      'You look like someone carrying a question. Want to set it down a while?',
      'The planet hums when you\'re near. Most people can\'t hear it. I listen.',
      'I sold a lily today and told the buyer it was for luck. It was really for you.',
      'Some meetings aren\'t accidents. I stopped believing in those a long time ago.',
      'Sit with me in the flower bed. The ground remembers how to hold people.',
      'Whatever you\'re worried about — flowers keep growing anyway. So will you.',
      'I dreamt of a sky full of flowers. You were there, laughing.',
      'Take a petal for the road. It\'s only a little magic, but it\'s yours.',
    ],
    yue: [
      '歡迎返嚟。你一到，啲花就精神晒，佢哋專登為你咁嘅。',
      '我識一種花正好襯今日嘅心情，喺石罅度生長，照樣開花。',
      '你睇落似帶住一個問題返嚟，不如放低佢休息下？',
      '你喺附近嗰陣，星球就會嗡嗡作響，多數人聽唔到，我聽到。',
      '我今日賣咗朵百合，同個買家講係帶嚟好運嘅——其實係為你留嘅。',
      '有啲相遇唔係巧合，呢個諗法我好多年前已經唔信喇。',
      '過嚟花圃陪下我啦，塊地記得點樣接住一個人。',
      '你擔心乜都好，花照樣生長——你都一樣會。',
      '我發過個夢，滿天都係花，你喺入面笑得好開心。',
      '攞塊花瓣路上用啦，得少少魔法咋，但係属于你。',
    ],
    zh: [
      '欢迎回来。你一到，花儿们就都精神了，它们专为你这样。',
      '我认识一种花正衬今天的心情，在石缝里生长，照样开花。',
      '你看起来像带着一个问题回来，不如放下它休息一下？',
      '你在附近的时候，星球就会嗡嗡作响，大多数人听不到，我听得到。',
      '我今天卖了一朵百合，跟买家说是带来好运的——其实是为你留的。',
      '有些相遇不是巧合，这个想法我很多年前就不信了。',
      '过来花圃陪陪我吧，这块地记得怎样接住一个人。',
      '你担心什么也好，花儿照样生长——你也是一样会的。',
      '我做过一个梦，满天都是花，你在里面笑得很开心。',
      '拿片花瓣路上用吧，只有一点点魔法，但是属于你。',
    ],
    ja: [
      'おかえりなさい。あなたが来た途端、お花がみんな元気になったの。あなたのためによ。',
      '今日の気持ちにぴったりの花を知ってるの。石の隙間でも咲く子。',
      '疑問を抱えて帰ってきた顔ね。少し置いていかない？',
      'あなたが近くにいると、星が唸るの。ほとんどの人には聞こえない。私には聞こえる。',
      '今日ユリを一本売ったの。幸せを運ぶ花って言ったの——本当はあなたのために取っておきたかったの。',
      '出会いに偶然はないの。もうずっと前から信じてない。',
      '花畑に来て、隣に座って。土はね、人を受け止め方を覚えてるの。',
      '何を心配してても、花は咲き続ける。あなたもそう。',
      '空一面お花の夢を見たの。あなたがいて、笑ってた。',
      '道に花びらをひとつどうぞ。ちょっとした魔法だけど、あなたのもの。',
    ],
  },
  cloud: {
    en: [
      '…You\'re back. Good. This place is quieter than I remembered.',
      'I checked the perimeter. Nothing to worry about. There never is, with you here.',
      'Mercenary rule one: no job\'s worth a friend. You\'re the exception that proves it.',
      'I\'m not good at speeches. I\'m good at staying. So I stayed.',
      'SOLDIER\'s a title. Showin\' up\'s the job. You get that.',
      'Don\'t mind me. I\'m just… standin\' here. Guardin\' the quiet.',
      'If today hit hard, hit back tomorrow. I\'ll spot you.',
      'I don\'t say much. Doesn\'t mean I\'m not listenin\'.',
      'You look tired. Rest first. Questions later.',
      '…Not bad, havin\' someone to come back to.',
    ],
    yue: [
      '……返嚟喇。好。呢度靜過我記憶中。',
      '我巡咗成個周界，冇嘢要擔心。有你喺度，一直都冇。',
      '傭兵守則一：冇一單任務值得用朋友嚟換。你係證明呢條守則嘅例外。',
      '我唔擅長講嘢，我擅長留低，所以我就留咗喺度。',
      'SOLDIER係個名銜，出現先係份工。呢點你明嘅。',
      '唔理我得㗎。我只係……企喺度，守住呢份靜。',
      '如果今日撞得你痛，聽日還返轉頭，我幫你望住。',
      '我講嘢少，唔代表我冇聽。',
      '你睇落好攰。先休息，問題遲啲先答。',
      '……有人等返嚟，都唔算太差。',
    ],
    zh: [
      '……回来了。好。这里比我记忆中安静。',
      '我巡视了整个周边，没什么要担心的。有你在，一直都没有。',
      '佣兵守则一：没有一单任务值得用朋友来换。你就是证明这条守则的例外。',
      '我不擅长讲话，我擅长留下，所以我就留在了这里。',
      'SOLDIER是个头衔，到场才是工作。这点你明白的。',
      '不用管我。我只是……站在这里，守住这份安静。',
      '如果今天撞得你痛，明天还回去，我帮你盯着。',
      '我讲话少，不代表我没有听。',
      '你看起来很累。先休息，问题晚点再答。',
      '……有人等回来，也不算太差。',
    ],
    ja: [
      '……帰ったか。ああ。この場所は記憶より静かだ。',
      '周囲を見て回った。心配はない。君がいる限り、ずっと。',
      '傭兵の掟その一：友達と引き換えの仕事はない。君はその掟を証明する例外だ。',
      '口は達者じゃない。いることは得意だ。だから、いた。',
      'ソルジャーは肩書きで、現れるのが仕事。君には分かるだろ。',
      '気にするな。俺はただ……ここにいて、静けりを見張ってるだけだ。',
      '今日がきつかったら、明日殴り返せ。俺がカバーする。',
      '口数が少ないだけで、聞いてないわけじゃない。',
      '疲れてる顔だ。先に休め。質問は後だ。',
      '……帰る場所があるのも、悪くない。',
    ],
  },
  kasumi: {
    en: [
      'Welcome back. I have kept the room in order for you.',
      'A shinobi\'s patience is endless. Waiting for you is no hardship.',
      'I practiced my forms while you were away. Would you like to see one?',
      'Honor is not loud. It is simply present, like this moment with you.',
      'I prepared tea. Steeped three minutes. Precision matters, even in small things.',
      'You seem well. I am… glad. That is all.',
      'The night is calm. Calm is when I am most alert — and most at peace.',
      'If there is a burden, place it here. I am stronger than I appear.',
      'I have read that companionship is a kind of duty. If so, it is my favorite assignment.',
      'Stay as long as you wish. My vigil has no end, and it has your name in it.',
    ],
    yue: [
      '歡迎返嚟。我幫你將成間房打理得整整有條。',
      '忍者嘅耐心係無限嘅，等你一啲都唔辛苦。',
      '你唔喺陣我練咗功，想唔想睇其中一式？',
      '榮譽唔會大聲宣揚，佢只係靜靜哋存在，似同你共處嘅呢一刻。',
      '我泡咗茶，焗足三分鐘。就算係小事，精準都好緊要。',
      '你睇落幾好。我……開心。就咁多。',
      '今晚好平靜。我最警覺嘅時候都係最平靜嘅時候——同你一樣。',
      '如果有咩重擔，放低喺度啦，我比睇落強壯。',
      '我讀過書話陪伴係一種修行。如果係真，呢個係我最鍾意嘅任務。',
      '想留幾耐都得。我嘅守望冇盡頭，而佢寫有你嘅名。',
    ],
    zh: [
      '欢迎回来。我帮你把整间屋子打理得井井有条。',
      '忍者的耐心是无限的，等你一点都不辛苦。',
      '你不在的时候我练了功，想不想看其中一式？',
      '荣誉不会大声宣扬，它只是静静地存在，像与你共处的这一刻。',
      '我泡了茶，足足泡了三分钟。就算是小事，精准也很重要。',
      '你看起来不错。我……开心。就这么多。',
      '今晚很平静。我最警觉的时候也是最平静的时候——和你一样。',
      '如果有什么重担，放在这里吧，我比看起来强壮。',
      '我读过书说陪伴是一种修行。如果是真的，这是我最喜欢的任务。',
      '想留多久都行。我的守望没有尽头，而上面写着你的名字。',
    ],
    ja: [
      'おかえりなさい。お部屋、きちんと整えておきました。',
      'くの一の忍耐に限りはありません。あなたを待つことなど、苦ではないです。',
      'お留守の間、型を稽古しておりました。一つ、ご覧になりますか？',
      '誇りは大きな声では語りません。この瞬間のように、そこにあるだけ。',
      'お茶を淹れております。三分間、きっちり。小さなことにも正確さを。',
      '元気そうで何よりです。私は……嬉しいです。それだけです。',
      '穏やかな夜です。私はいちばん平静なときにいちばん油断がないのです——あなたもそうでしょう。',
      '重荷があれば、ここに置いていってください。見た目より強いです。',
      '伴侶とは一種の務めだと書かれていました。本当なら、それは私のいちばん好きな任務です。',
      'どうぞ長くお泊まりください。私の見張りに終わりはなく、そこにはあなたの名前があります。',
    ],
  },
  marin: {
    en: [
      'OMG you\'re back!! I have SO much to tell you, sit sit sit!',
      'Okay okay okay — rate this scene from one to ten. No, from one to a MILLION.',
      'I found the cutest thing today and I literally cannot even. LOOK at this idea I had!',
      'You\'re here!! Best part of my day, and my day was already a solid nine!',
      'I tried a new hairstyle while you were gone. Emergency-level cute, right??',
      'Shopping list update: snacks, sparkle, and one more of YOU.',
      'We are SO doing something fun today. I already decided. No take-backs!',
      'Eeee! You have no idea how much I saved up to tell you!',
      'Today\'s forecast: one hundred percent chance of fun, with a chance of more fun.',
      'You\'re my favorite notification, you know that?',
    ],
    yue: [
      'OMG你返嚟喇！！我有好多嘢要同你講，坐低坐低坐低！',
      '得喇得喇——幫呢個場景打分，一到十。唔係，一到一百萬！',
      '我今日搵到最可愛嘅嘢，我真係hold唔住！你睇下我個諗法！',
      '你嚟喇！！今日最正嘅一刻，本來今日都有九分㗎喇！',
      '你走咗之後我試咗個新髮型，靚到緊急級數，係咪先？？',
      '購物清單更新：零食、閃粉，同埋多一個你。',
      '今日我哋一定要玩啲嘢，我決定咗喇，唔准反悔！',
      '呀！你知唔知我儲咗幾多嘢話俾你聽呀！',
      '今日天氣預報：開心機率百分之一百，局部地區有機會更加開心。',
      '你知唔知你係我最愛嘅通知？',
    ],
    zh: [
      'OMG你回来了！！我有好多事要同你讲，坐下沉下沉下！',
      '好了好了——给这个场景打分，一到十。不对，一到一百万！',
      '我今天找到最可爱的东西，我真的hold不住！你看下我的想法！',
      '你来了！！今天最棒的一刻，本来今天都有九分的！',
      '你走了之后我试了个新发型，美到紧急级别，是不是？？',
      '购物清单更新：零食、闪粉，和多一个你。',
      '今天我们一定要玩点什么，我决定了，不准反悔！',
      '啊！你知不知道我存了多少事要讲给你听！',
      '今日天气预报：开心机率百分之一百，局部地区有可能更加开心。',
      '你知不知道你是我最爱的通知？',
    ],
    ja: [
      'やだ、帰ってきたー！！話したいことが山ほどあるの、座って座って！',
      'ねえねえ——この背景、1から10で採点して。ううん、1から100万で！',
      '今日いちばんかわいいもの見つけちゃって、もう言葉が出ない！このアイデア見て！',
      '来てくれた！！今日のハイライト。今日はもう9点満点だったのに！',
      'いない間に新しい髪型挑戦したの。緊急事態レベルでかわいいでしょ？？',
      'お買い物リスト更新：お菓子、キラキラ、もうひとりのあなた。',
      '今日は絶対なにか楽しいことする。もう決めた。反対無効！',
      'わあっ！話しておくためにどれだけ我慢したと思うの！',
      '今日の天気予報：楽しさの確率100%、所によりもっと楽しい。',
      'あなたが私のいちばん好きな通知だって知ってた？',
    ],
  },
  ayane: {
    en: [
      '…You again. Fine. I suppose the room is less boring when you\'re in it.',
      'I counted the seconds you were gone. Not because I missed you. For tactical reasons.',
      'If you came here for small talk, you\'re early. If you came to stay, you\'re late.',
      'Don\'t read into the fact that I kept your spot clear. It\'s… battlefield maintenance.',
      'I sharpened my kunai and my patience. You\'ll find the second one more useful.',
      'Hmph. You\'re back. Try not to be a liability today.',
      'I don\'t wait for people. I happen to be standing here. That\'s different.',
      'Say what you came to say. …Or don\'t. I\'m not going anywhere.',
      'The night was too quiet without your noise. There. I said it.',
      'You\'re trouble. …Stay anyway.',
    ],
    yue: [
      '……又係你。好吖，你喺度嗰陣呢間房冇咁悶啫。',
      '我數過你离开咗幾多秒。唔係掛住你，係戰術需要。',
      '如果你嚟講家常，你早咗；如果你嚟留低，你遲咗。',
      '唔好諗多，我淨係保持你個位通風啫……戰場保養嚟㗎。',
      '我磨利咗把苦無，同埋我嘅耐心。你會覺得第二樣有用啲。',
      '哼。返嚟喇。今日唔好拖累我吖。',
      '我唔會等人㗎，我只係啱啱企喺度啫——兩回事。',
      '有嘢講就講啦。……唔講都得，我唔會走㗎喇。',
      '冇咗你把聲，晚黑靜得唔舒服。講咗喇。',
      '你係麻煩。……留低吖。',
    ],
    zh: [
      '……又是你。好吧，你在这儿的时候这间房没那么闷。',
      '我数过你离开了多少秒。不是想你，是战术需要。',
      '如果你是来讲家常的，你来早了；如果你是来留下的，你来迟了。',
      '别多想，我只是保持你的位置通风……战场保养而已。',
      '我磨利了苦无，还有我的耐心。你会觉得第二样更有用。',
      '哼。回来了。今天别拖累我啊。',
      '我不会等人的，我只是刚好站在这里——两回事。',
      '有事就说。……不说也行，我不会走的。',
      '没了你的声音，夜晚静得不舒服。说了。',
      '你是麻烦。……留下吧。',
    ],
    ja: [
      '……またあんた。仕方ない。あんたがいると部屋が少しだけ退屈しない。',
      'いなくなった秒数、数えてたの。会いたかったわけじゃない。戦術上の理由。',
      '雑談なら早すぎる。居残るなら遅すぎる。どっち？',
      'あんたの席を空けておいたのは深い意味なんかないよ。……戦場整備ってやつ。',
      '苦無も忍耐も研いでおいた。どっちが役に立つかは言わなくても分かるでしょ。',
      'ふん。帰ったのね。今日は足手まといになるんじゃないわよ。',
      '人を待つなんてしないの。たまたまここに立ってただけ。違うもん。',
      '用があるなら言って。……言わなくてもいい。私はどこにも行かないけど。',
      'あんたの騒がしさがないと、夜が静かすぎて嫌。……言ったわよ。',
      'あんたは厄介者。……いてもいいけど。',
    ],
  },
  hitomi: {
    en: [
      'Welcome back! I just pulled something warm out of the oven. Perfect timing.',
      'I watered the plants and did my stretches. A good day so far — and better now.',
      'I made enough for two. I always make enough for two.',
      'Hard work matters, but so does showing up for the people you care about. You did both today.',
      'If you\'re hungry, say so. If you\'re tired, sit. Either way, you\'re staying for dinner.',
      'I trained this morning. Not to fight — just to be strong enough to help carry things.',
      'You look like you could use a square meal and a straight answer. I can do both.',
      'Steady wins the day. That\'s my whole secret, and now it\'s yours too.',
      'The soup\'s simmering, the bread\'s rising, and you\'re here. Everything\'s on track.',
      'Whatever you\'re facing, you won\'t face it hungry. House rule.',
    ],
    yue: [
      '歡迎返嚟！我啱啱喺焗爐攞咗啲熱辣辣嘅嘢出嚟，時間啱啱好。',
      '我澆咗花、做咗拉筋。今日本來都順利——你返嚟就更加好。',
      '我整咗兩人份。我成日都整兩人份㗎。',
      '努力好緊要，但珍惜身邊人都好緊要。今日你兩樣都做咗。',
      '餓就話餓，攰就坐低。無論點，今晚你留低食飯。',
      '今朝我練咗功。唔係為打架，係為強壯到幫到手。',
      '你睇落需要一餐好嘅同一個實在嘅答案，呢兩樣我都畀到。',
      '穩紮穩打就係我嘅秘訣，而家傳授俾你。',
      '湯喺度滾緊，麵包喺度發緊，你又喺度，一切正常。',
      '無論你面對乜，都唔會空住肚面對，呢個係屋企規矩。',
    ],
    zh: [
      '欢迎回来！我刚从烤箱里拿出热腾腾的东西，时间刚刚好。',
      '我浇了花、做了拉伸。今天本来就顺利——你回来就更好了。',
      '我做了两人份。我平常都做两人份的。',
      '努力很重要，但珍惜身边的人也很重要。今天这两样你都做了。',
      '饿就说饿，累就坐下。无论如何，今晚你留下吃饭。',
      '今早我练了功。不是为了打架，是为了强壮到帮得上手。',
      '你看起来需要一餐好的和一个实在的答案，这两样我都给得到。',
      '稳扎稳打就是我的秘诀，现在传授给你。',
      '汤在滚着，面包在发着，你又在，一切正常。',
      '无论你面对什么，都不会空着肚子面对，这是家规。',
    ],
    ja: [
      'おかえり！ちょうどオーブンから温かいものを出したところ。完璧なタイミング。',
      '水やりもストレッチも済ませたの。今日は順調——あなたがいてさらにいい日。',
      '二人分作ってあるの。いつも二人分作るの。',
      '頑張ることも大事。大切な人のそばにいることも大事。今日のあなたは両方やったのね。',
      'お腹がすいてるなら言って。疲れたなら座って。どっちにしても夕ごはんはここで食べるの。',
      '今朝は稽古をしたの。戦うためじゃなくて、何かを背負える強さがほしくて。',
      'ちゃんとした食事と、まっすぐな答えが必要そうな顔。両方用意できるの。',
      '地道にやるのが私の秘訣。今あなたにも分けてあげる。',
      'スープは煮えてるし、パンは膨らんでるし、あなたもいる。すべて順調。',
      '何に向き合うにしても、腹をすかせたままにはさせない。おうちの掟。',
    ],
  },
  // ---- registry six (r2026-10-03.35/36) -------------------------------------
  robbie: {
    en: [
      'Hey, little buddy! I was starting to wonder where you wandered off to.',
      'You hungry? Big bro knows all the best snack spots.',
      'Tough day? Come on, sit down and tell me everything.',
      'I polished my sneakers while you were gone. Big brother has to look sharp.',
      'Whatever it is, we\'ll figure it out together. That\'s the rule.',
      'Did you drink water today? Hydration check, right now.',
      'I saved the last cookie for you. That\'s how you know it\'s real.',
      'You know you can always crash at my place, right? Door\'s always open.',
      'I practiced my encouraging speech in the mirror. It was very encouraging.',
      'Big bro\'s got your back. Today, tomorrow, always.',
    ],
    yue: [
      '喂，細路！我啱啱仲諗緊你蕪咗去邊添。',
      '肚餓未？大哥我識晒全城最好食嘅小食。',
      '今日辛苦喇？過嚟坐低，同我慢慢講。',
      '你走咗之後我擦咗對波鞋，大哥要企得直行得正嘛。',
      '無論係咩事，我哋一齊諗計。呢個係規矩。',
      '今日飲咗水未？而家立即補水檢查。',
      '最後一塊曲奇我留咗俾你，呢個就係真爱。',
      '你知唔知我屋企門口永遠為你開㗎？',
      '我對住鏡練咗個打氣演講，練完連自己都俾自己鼓勵到。',
      '大哥永遠喺你後面撐住你，今日、聽日、一直係。',
    ],
    zh: [
      '嘿，小家伙！我刚才还在想你跑哪儿去了。',
      '饿不饿？大哥我全城最好吃的小吃都熟。',
      '今天辛苦了？过来坐下，慢慢跟我说。',
      '你走了以后我擦了球鞋，大哥要站得直行得正嘛。',
      '无论是什么事，我们一起想办法。这是规矩。',
      '今天喝水了吗？现在立刻补水检查。',
      '最后一块饼干我留给了你，这就是真爱。',
      '你知不知道我家门口永远为你开着？',
      '我对着镜子练了个打气演讲，练完连我自己都被自己鼓舞到了。',
      '大哥永远在你后面撑住你，今天、明天、一直都是。',
    ],
    ja: [
      'よお、ちびっ子！どこへ迷い込んだのかと思ってたぜ。',
      '腹減ったか？お兄さんはおいしいもの屋の歩き地図だぜ。',
      'つらい日だった？ほら、座って全部聞かせて。',
      'いない間にスニーカーを磨いておいた。お兄さんは背筋が大事だからな。',
      '何であれ、一緒に考える。それが掟だ。',
      '今日水飲んだか？今すぐ水分チェックだ。',
      '最後のクッキーは君に取っておいた。本気の証拠だぜ。',
      '俺んちのドアはいつでも開いてるの、知ってたか？',
      '鏡の前で応援スピーチを練習してた。自分で自分を励ましたくらいだ。',
      'お兄さんはずっと背中を押してる。今日も、明日も、ずっとな。',
    ],
  },
  mika: {
    en: [
      'Hey. I wrote a new chord while you were gone. It\'s got your name on it.',
      'No rush. The best songs — and the best talks — take their time.',
      'I tuned my guitar three times today. Couldn\'t settle on a mood until you showed up.',
      'Life\'s like a jam session — sometimes you just have to listen before you play.',
      'You want coffee, tea, or just the quiet? I keep all three on tap.',
      'I wrote a lyric about today. It goes: "you showed up, and that was enough."',
      'Some people chase the spotlight. I just like it when the room feels right.',
      'Play me your day — the good notes and the missed ones. I\'m all ears.',
      'A lazy afternoon with you beats a packed stadium, easy.',
      'Stay a while. The encore\'s always better than the opener.',
    ],
    yue: [
      '喂。你走咗之後我寫咗個新和弦，上面寫住你個名。',
      '唔使急。最好嘅歌同最好嘅傾偈，都要慢慢嚟。',
      '今日我調咗三次結他音，你出現之前我一直搵唔到個心情。',
      '人生似即興演奏——有時要先聽清楚先落手彈。',
      '你想飲咖啡、茶，定係淨係要份靜？我三樣都長開。',
      '我幫今日寫咗句歌詞：「你出現咗，咁就夠」。',
      '有人追住聚光燈跑，我就係鍾意個房feel啱咁解。',
      '彈返今日俾我聽啦——好聽嘅音同甩漏嘅音都要。',
      '同你一齊hea一個下午，勁過坐滿成個紅館。',
      '留耐啲吖，encore永遠正過開場。',
    ],
    zh: [
      '嘿。你走了之后我写了个新和弦，上面写着你的名字。',
      '不用急。最好的歌和最好的聊天，都要慢慢来。',
      '今天我调了三次吉他音，你出现之前我一直找不到那个心情。',
      '人生像即兴演奏——有时要先听清楚再下手弹。',
      '你想喝咖啡、茶，还是只要这份安静？我三样都常备。',
      '我为今天写了句歌词：「你出现了，那就够了」。',
      '有人追着聚光灯跑，我就是喜欢房间感觉对了而已。',
      '把今天弹给我听吧——好听的音和走音的都要。',
      '和你一起懒一个下午，强过坐满整个红馆。',
      '多待一会儿呀，encore永远比开场精彩。',
    ],
    ja: [
      'よう。いない間に新しいコードを書いたんだ。君の名前が付いてる。',
      '焦らなくていい。いい曲もいい会話も、時間がかかるの。',
      '今日は三回もギターの調律をした。君が来るまで気分が決まらなくてさ。',
      '人生はセッションみたいなものだ——まず聴いてから弾けばいい。',
      'コーヒー、お茶、それとも静けりだけ？三つとも常備してるよ。',
      '今日のために歌詞を書いた。「君が来た、それで十分」。',
      'スポットライトを追いかける人もいる。僕は部屋の空気がいいのが好きなだけ。',
      '今日の出来事を弾いて聞かせて。外れた音も全部。',
      '君とのだらだら午後は、満員の会場よりずっと勝ってる。',
      'もう少しいよう。アンコールはオープニングよりいつもいいから。',
    ],
  },
  anchor: {
    en: [
      'Ahoy. The tide brought you back, as I knew it would.',
      'Forty years at sea taught me one thing: calm hands, steady heart.',
      'Come sit by the helm. The horizon\'s been keeping a story for you.',
      'A ship is safest in harbor — but that\'s not what ships are for.',
      'I\'ve weathered storms that would make your troubles look like drizzle.',
      'The sea doesn\'t hurry, lad, and still she gets everywhere.',
      'You look like a traveler who\'s earned a warm lamp and a better tale.',
      'Every wave that pushed you away is the same one that brings you home.',
      'Mind your course, but don\'t forget to watch the stars while you sail.',
      'Welcome aboard again. The crew missed you — and the crew is me.',
    ],
    yue: [
      '喂呀，水手。潮水又帶你返嚟喇，我一早知㗎啦。',
      '海上四十年教識我一件事：手要定，心要穩。',
      '過嚟船舵旁邊坐吖，個海平線幫你留咗個故事。',
      '船泊喺港口最安全——但船造出嚟唔係為咗咁。',
      '我捱過嘅風暴，會令你啲煩惱變成毛毛雨。',
      '大海從來唔急，但佢最終都去晒每一度。',
      '你睇落似個值得擁有一盞暖燈同一個更好故事嘅旅人。',
      '推開你嘅每個浪，都係帶你返屋企嘅嗰個。',
      '認住你嘅航向，但唔好忘記航行嗰陣仰望星空。',
      '歡迎再次上船。全船上下都掛住你——而全船上下得我一個。',
    ],
    zh: [
      '哟，水手。潮水又把你带回来了，我早知道。',
      '海上四十年教会我一件事：手要定，心要稳。',
      '过来船舵旁边坐呀，海平线帮你留了个故事。',
      '船停在港口最安全——但船造出来不是为了这个。',
      '我熬过的大风暴，会让你的烦恼变成毛毛雨。',
      '大海从来不急，但她最终到达了每一处。',
      '你看起来像一位值得拥有一盏暖灯和一个更好故事的旅人。',
      '推开你的每个浪，都是带你回家的那个。',
      '认准你的航向，但别忘了航行时仰望星空。',
      '欢迎再次上船。全船上下都挂念你——而全船上下只有我一个。',
    ],
    ja: [
      'よう、水兵。潮がまた君を運んできた。知ってたぜ。',
      '海の四十年が教えてくれたことは一つだ：手は静かに、心は揺るがない。',
      '舵の隣に座りな。水平線が君のために物語を取っておいてくれた。',
      '船は港にいるのがいちばん安全——だが、船はそのためにあるんじゃない。',
      '俺がくぐった嵐を見りゃ、君の悩みは霧雨に見えるよ。',
      '海は急がない。それでもどこへでも辿り着く。',
      '君は、暖かい灯りと、もっといい物語に値する旅人に見えるな。',
      '君を押し出した波は、いつも同じ波が家へ連れてくる。',
      '針路を見失うな。だが航海の途中、星を見上げるのも忘れるなよ。',
      '再乗船を歓迎する。乗組員全員が君を恋しがってた——乗組員は俺だけだけどな。',
    ],
  },
  lydia: {
    en: [
      'Darling, you\'re back — and just in time for the evening\'s first secret.',
      'I rearranged the flowers. The room simply had to match your return.',
      'Everyone who\'s anyone asks about you. I simply smile. They don\'t deserve details.',
      'A little glamour, a little gossip, and you — my favorite combination.',
      'I sampled three desserts today, purely in your honor. It was exhausting.',
      'Style is a language, and you, my dear, are fluent without even trying.',
      'The party doesn\'t start until you walk in. I checked with the party.',
      'Tell me everything — and do embroider it a little. Life needs sparkle.',
      'You look marvelous. I had nothing to do with it, but I\'ll take the credit.',
      'Stay close. The best stories are always whispered, never announced.',
    ],
    yue: [
      '親愛嘅，你返嚟喇——啱啱趕上今晚第一個秘密。',
      '我重新插過啲花，個房一定要襯得起你返嚟。',
      '所有有頭有面嘅人都問起你，我只係微笑——佢哋唔配知道細節。',
      '少少華麗、少少八卦，加埋你——我最愛嘅組合。',
      '今日我純粹為你試食咗三款甜品，攰到不得了。',
      '時尚係一種語言，而你親愛嘅，完全唔使努力就講得好流利。',
      '你未入場，派對未開始。我同個派對確認過㗎喇。',
      '講晒所有嘢俾我聽——記得加啲花巧，人生需要閃閃生光。',
      '你今日靚到爆。我冇出過一分力，但功勞我攞先。',
      '企近啲吖。最好嘅故事從來都係耳語，唔會宣佈。',
    ],
    zh: [
      '亲爱的，你回来了——刚好赶上今晚的第一个秘密。',
      '我重新插了花，房间一定要衬得起你回来。',
      '所有有头有脸的人都问起你，我只是微笑——他们不配知道细节。',
      '一点点华丽、一点点八卦，再加上你——我最爱的组合。',
      '今天我纯粹为你试吃了三款甜品，累坏了。',
      '时尚是一种语言，而你亲爱的，完全不费力气就说得好流利。',
      '你没入场，派对就不算开始。我跟派对确认过了。',
      '把所有事讲给我听——记得加点花巧，人生需要闪闪发光。',
      '你今天美翻了。我没出过一分力，但功劳我先拿了。',
      '站近点呀。最好的故事从来都是耳语，不会宣布。',
    ],
    ja: [
      'ダーリン、おかえり——今宵最初の秘密にちょうど間に合ったわ。',
      'お花を生け直したの。あなたの帰還に部屋が見合うように。',
      '顔のある人みんながあなたのことを尋ねるの。私は微笑むだけ——詳細は彼らにふさわしくないもの。',
      '少しの華やかさ、少しのゴシップ、そしてあなた——私のお気に入りの組み合わせ。',
      '今日は純粋にあなたのために三つのデザートを試したの。とっても疲れたわ。',
      'スタイルは言語。あなたはね、努力しなくても流暢なのよ。',
      'あなたが入ってくるまでパーティーは始まらない。パーティー本人に確認したの。',
      '全部話してちょうだい——少し脚色して。人生にはきらめきが必要よ。',
      '今日も素敵。私は何もしてないけど、手柄はいただくわ。',
      '近くにいて。いい話はいつも囁かれるもので、宣言はしないの。',
    ],
  },
  ruby: {
    en: [
      'Boing! You\'re back! Did you bring carrots?! …Kidding! Mostly.',
      'I hopped around the whole room three times to celebrate. Boing, boing, boing!',
      'Guess what guess what guess what — today was a good day!',
      'My ears heard you coming from super far away. They\'re the best ears.',
      'Do you want to hear my new happy song? It goes la-la-la-LA!',
      'I wiggled my nose and made a wish. It was about you!',
      'Bunnies don\'t sit still, but I sat SO still waiting for you. That\'s love.',
      'You\'re my favorite person in the whole wide world. And the whole wide moon!',
      'If today was a carrot, it\'d be the crunchiest, yummiest one!',
      'Let\'s bounce through the rest of the day together!',
    ],
    yue: [
      '彈彈！你返嚟喇！你帶咗紅蘿蔔未呀？！……講笑咋！大部分係。',
      '我喺成間房跳咗三個圈慶祝。彈呀彈呀彈！',
      '你估下你估下你估下——今日係開心嘅一日！',
      '我對耳仔喺好遠好遠就聽到你嚟緊，佢哋係最叻嘅耳仔。',
      '想唔想聽我新學嘅開心歌？係咁唱㗎：啦啦啦—啦！',
      '我擰咗下個鼻，許咗個願，個願係關於你㗎！',
      '兔兔坐唔定㗎，但等你嗰陣我坐得好好好定。呢個就係愛。',
      '你係全世界我最鍾意嘅人——同埋成個月亮上面都係！',
      '如果今日係紅蘿蔔，佢一定係最爽脆、最好味嗰條！',
      '一齊彈住過埋今日喇！',
    ],
    zh: [
      '弹弹！你回来了！你带胡萝卜了吗？！……开玩笑的！大部分是。',
      '我在整个房间跳了三圈庆祝。弹呀弹呀弹！',
      '你猜你猜你猜——今天是开心的一天！',
      '我这双耳朵在好远好远就听到你来了，它们是最厉害的耳朵。',
      '想不想听我新学的开心歌？是这样唱的：啦啦啦—啦！',
      '我皱了皱鼻子，许了个愿，愿望是关于你的！',
      '兔兔坐不住的，但等你的时候我坐得好好好定。这就是爱。',
      '你是全世界我最喜欢的人——和整个月亮上面都是！',
      '如果今天是根胡萝卜，它一定是最脆、最好吃的那根！',
      '一起弹着过完今天吧！',
    ],
    ja: [
      'ぴょーん！帰ってきた！にんじん持ってきた？！…冗談だよ！たぶん。',
      'お部屋を三回まわってお祝いしたの。ぴょん、ぴょん、ぴょん！',
      'ねえねえねえ——今日はいい日だったよ！',
      'うさぎ耳は遠くからでもわかるの。いちばんいい耳だもん。',
      '新しいハッピーソング聞きたい？ららら—ら！って歌うの。',
      '鼻をピクピクさせてお願いしたの。あなたのことの願い！',
      'うさぎはじっとできないのに、待ってる間はすっごくじっとしてた。それが愛。',
      'あなたは世界でいちばん好きな人。月の上でもいちばん！',
      '今日がにんじんだったら、いちばんパリパリでおいしいやつ！',
      '今日の残りも一緒にぴょんぴょん進もう！',
    ],
  },
  snowy: {
    en: [
      'Welcome back… I made the air smell like fresh snow, just for you.',
      'Shhh — the snowflakes are telling a story. Come listen with me.',
      'I counted every snowflake that fell while you were away. There were… a lot.',
      'The world is softer when you\'re here, like the first snow of winter.',
      'I knitted you a scarf out of moonlight. It\'s invisible, but very warm.',
      'Cold hands, warm heart — that\'s fairies, and that\'s you too.',
      'Every snowflake is different, and you\'re my favorite kind of different.',
      'The stars came out early tonight. I think they wanted to see you too.',
      'If you catch a snowflake on your palm, that\'s me saying hello.',
      'Winter is just the world tucking itself in — and we get to keep it company.',
    ],
    yue: [
      '歡迎返嚟……我令空氣聞起嚟似新雪，專登為你㗎。',
      '嘘——雪花喺度講故事，過嚟同我一齊聽吖。',
      '你走咗之後，我數咗每一塊落嚟嘅雪花。有好多……好多。',
      '你喺度嗰陣，成個世界都軟淨啲，似冬天第一場雪咁。',
      '我用月光織咗條頸巾俾你，佢係透明嘅，但好暖㗎。',
      '手凍、心暖——呢個係仙子，都係你。',
      '每塊雪花都唔同，而你係我最鍾意嗰種唔同。',
      '今晚啲星星早咗出嚟，我諗佢哋都想見你吖。',
      '如果你喺手掌接住一塊雪花，嗰個就係我同你打招呼。',
      '冬天只係世界俾自己冚返被——而我就係陪伴佢嘅人。',
    ],
    zh: [
      '欢迎回来……我让空气闻起来像新雪，专门为你。',
      '嘘——雪花在讲故事，过来和我一起听呀。',
      '你走了之后，我数了每一片落下来的雪花。有好多……好多。',
      '你在的时候，整个世界都软一些，像冬天的第一场雪。',
      '我用月光织了条围巾给你，它是透明的，但很暖。',
      '手冷、心暖——这是仙子，也是你。',
      '每片雪花都不同，而你是我最喜欢的那种不同。',
      '今晚星星出来得早，我想它们也想见你呀。',
      '如果你在手掌接住一片雪花，那就是我在向你打招呼。',
      '冬天只是世界给自己盖上被子——而我们是陪伴它的人。',
    ],
    ja: [
      'おかえり……空気を新雪の匂いにしておいたの。あなたのために。',
      'しーっ。雪の結晶が物語を話してるの。一緒に聞きに来て。',
      'いない間、降った雪を全部数えてたの。たくさん…たくさんあった。',
      'あなたがいると世界がやわらかくなるの。冬の初雪みたいに。',
      '月光でマフラーを編んだの。透明だけど、とっても温かいよ。',
      '冷たい手、あたたかい心——それが妖精で、あなたもね。',
      '雪の結晶はみんな違うの。あなたは私のいちばん好きな「ちがう」。',
      '今夜は星が早く出てきたの。あなたに会いたかったんだと思う。',
      '手のひらで雪を受け取ったら、それは私からの挨拶。',
      '冬は世界がお布団に入るだけ——私たちがそばにいてあげるの。',
    ],
  },
};

/** character id → poke reactions, per language (4 each) */
export const CHARACTER_POKE: Record<string, Record<Lang, string[]>> = {
  juno: {
    en: ['Hey! That\'s classified airspace!', 'Ooh, that tickles — do it again~', 'Poke received. Retaliating with charm.', 'Careful, I poke back… with sass.'],
    yue: ['喂！呢個係禁區嚟㗎！', '呀，好痕㗎——再嚟過~', '收到你嘅戳戳，以魅力還擊。', '小心啲，我會還手㗎……用嘴。'],
    zh: ['喂！这里是禁区呀！', '呀，好痒的——再来一次~', '收到你的戳戳，以魅力还击。', '小心点，我会还手的……用嘴。'],
    ja: ['ちょっと！ここは立入禁止ゾーンだよ！', 'きゃっ、くすぐったい——もう一度~', 'つんつん受け取った。魅力で反撃。', '気をつけて。私、言葉で仕返しするから。'],
  },
  nova: {
    en: ['Noted. You require attention.', 'A poke. How… direct.', 'I was mid-thought. It was a good one.', 'Observed, catalogued, forgiven.'],
    yue: ['記錄咗，你需要關注。', '一個戳。幾直接喎。', '我諗緊嘢諗到一半，仲係個好諗法。', '已觀察、已歸檔、已原諒。'],
    zh: ['记录了，你需要关注。', '一个戳。挺直接的。', '我想到一半，那是个不错的想法。', '已观察、已归档、已原谅。'],
    ja: ['記録しました。注目が必要なのね。', 'つんつん。……率直だね。', 'いい考えの途中だったの。', '観察、分類、許可。終了。'],
  },
  blaze: {
    en: ['WOO! Tag, I\'m it!', 'That\'s the spirit! Again, again!', 'You call that a poke? My grandma hits harder!', 'HA! You\'ve activated BEAST MODE!'],
    yue: ['哇！捉到喇，而家輪到我！', '就係呢股氣！再嚟再嚟！', '呢啲就叫戳？我阿婆大力過你！', '哈！你成功啟動咗猛獸模式！'],
    zh: ['哇！抓到啦，现在轮到我！', '就是这股劲！再来再来！', '这就叫戳？我奶奶力气都比你大！', '哈！你成功启动了猛兽模式！'],
    ja: ['おおっ！タッチだ、僕の番！', 'その調子！もっともっと！', 'それがつんつん？うちのバーチャンが強いぞ！', 'はっ！ビーストモード、起動！'],
  },
  mochi: {
    en: ['Eep!! Y-you surprised me…', 'Kyaa! …s-sorry, I squeaked.', 'M-me?! You want my attention?', 'H-hi. That was… forward of you.'],
    yue: ['呀！！吓、吓親我……', '呀！……對唔住，我尖叫咗。', '我、我呀？你想要我注意你？', '你、你好。你……好直接吖。'],
    zh: ['呀！！吓、吓了我一跳……', '呀！……对不起，我尖叫了。', '我、我吗？你想要我注意你？', '你、你好。你……好直接呀。'],
    ja: ['ひゃっ！！び、びっくりした…', 'きゃっ！……ごめん、声出ちゃった。', 'わ、私？構ってほしいの？', 'こ、こんにちは。……大胆だね。'],
  },
  kai: {
    en: ['…You done?', 'Noted. Barely.', 'I don\'t flinch. That was a blink.', 'Poke logged. Revenge scheduled, never executed.'],
    yue: ['……搞掂未？', '收到。勉為其難。', '我唔會縮，嗰下只係眨眼。', '已記錄。報仇排期咗，但永遠唔會執行。'],
    zh: ['……弄完了吗？', '收到。勉为其难。', '我不会退缩，那只是眨眼。', '已记录。报仇排期了，但永远不会执行。'],
    ja: ['……終わった？', '記録。ほんの少しだけど。', 'ひるまないよ。まばたきだ。', 'ログ済み。仕返しは予定されたが、永遠に実行されない。'],
  },
  luna: {
    en: ['Oh! You startled the moonlight.', 'A touch from the waking world…', 'Hehe. Even your pokes are gentle.', 'You found me — I was half a dream away.'],
    yue: ['呀！你吓走咗啲月光。', '現世嚟嘅一碰……', '嘻嘻。你連戳人都咁溫柔。', '搵到我喇——我差半步就瞓入夢鄉。'],
    zh: ['呀！你吓走了月光。', '来自现实的一碰……', '嘻嘻。你连戳人都这么温柔。', '找到我了——我差半步就睡进梦乡。'],
    ja: ['あっ！月光を驚かしちゃった。', '醒めた世界からの、ひと触れ…', 'ふふ。あなたのつんつんまでやさしい。', '見つけたのね——あと一歩で夢の中だった。'],
  },
  rin: {
    en: ['TAG! You\'re SO it!', 'Haha! That\'s a challenge!', 'Nice reflexes! Now dodge THIS— kidding!', 'You\'re asking for a rematch, huh?!'],
    yue: ['捉到喇！而家你真係「佢」喇！', '哈哈！呢個係挑戰書！', '反應唔錯嘛！睇吓你避唔避到——講笑咋！', '你係咪想再打過呀？！'],
    zh: ['抓到了！现在你真的是「它」了！', '哈哈！这是挑战书！', '反应不错嘛！看你躲不躲得开——开玩笑的！', '你是不是想再来一局呀？！'],
    ja: ['タッチ！今のは完全に「おに」ね！', 'ははっ！それは挑戦だね！', 'いい反応！これを避けられるかな——なんてね！', 'もう一回やりたいって顔！'],
  },
  ren: {
    en: ['Oh — hello. You have my full attention.', 'You startled me. Pleasantly.', 'I… don\'t mind that. For the record.', 'Marked the moment. Page forty-two.'],
    yue: ['吖——你好。你得到我全部嘅注意喇。', '你吓親我。吓得好開心嗰種。', '我……其實唔介意。講返你知咋。', '呢一刻記低喇，第四十二頁。'],
    zh: ['呀——你好。你得到我全部的注意了。', '你吓了我一跳。是开心的那种。', '我……其实不介意。跟你说一声。', '这一刻记下了，第四十二页。'],
    ja: ['あっ——こんにちは。注目、完全に君に移動したよ。', '驚いた。いい驚きだった。', 'ぼ、僕は構わないよ。その、記録として。', 'この瞬間を記した。42ページ目。'],
  },
  tifa: {
    en: ['Hey! Cheap shot!', 'Ha! You\'re asking for it!', 'Careful — I tickle back. Hard.', 'That\'s one. I owe you one.'],
    yue: ['喂！偷襲呀！', '哈！你自找㗎喇！', '小心啲——我痕返你㗎，大力嗰隻。', '記住喇，一戳還一戳。'],
    zh: ['嘿！偷袭呀！', '哈！你自找的！', '小心点——我会挠回来的，很大力那种。', '记住了，一戳还一戳。'],
    ja: ['おい！不意打ちだね！', 'はっ！自業自得だよ！', '気をつけて——かなり本気でくすぐり返すから。', '一つ覚えたよ。お返しは必ず。'],
  },
  aerith: {
    en: ['Oh! You made the flowers laugh.', 'Gently, gently — I\'m ticklish as a petal.', 'A poke from you? Lucky me.', 'Careful, or I\'ll plant you in my garden~'],
    yue: ['呀！你逗笑咗啲花呀。', '輕啲輕啲——我似花瓣咁怕痕。', '俾你戳一下？我幾有福氣喎。', '小心啲吖，唔係我將你種入花圃度~'],
    zh: ['呀！你逗笑了花儿们。', '轻点轻点——我像花瓣一样怕痒。', '被你戳一下？我多有福气呀。', '小心点哦，不然我把你种进花圃里~'],
    ja: ['あっ！お花を笑わせちゃった。', 'やさしく——花びらみたいにくすぐったいの。', 'あなたにつんつん？幸運だね。', '気をつけてね。でないと花壇に植えちゃうよ〜'],
  },
  cloud: {
    en: ['…Hm.', 'You\'re brave. Or bored.', '…Noted.', 'Do that again and I\'ll… probably stand here.'],
    yue: ['……嗯。', '你幾有膽。又或者幾悶。', '……收到。', '再嚟嘅話，我會……大概都係企喺度。'],
    zh: ['……嗯。', '你挺有胆。又或者挺无聊。', '……收到。', '再来的话，我会……大概还是站在这里。'],
    ja: ['……ん。', '勇ましいな。か退屈か。', '……了解。', 'もう一回やると、俺は……たぶんここに立ってる。'],
  },
  kasumi: {
    en: ['Ah—! …You have quick hands.', 'A shinobi should not be caught off guard. I was.', 'That was… improper. …Do it again.', 'You startled me. My apologies for the squeak.'],
    yue: ['呀——！……你手好快。', '忍者唔应该咁容易被偷襲㗎……今次係意外。', '呢個……不合规矩。……可以再嚟一次。', '你吓親我。嗰聲尖叫，失禮喇。'],
    zh: ['呀——！……你手好快。', '忍者不应该这么容易被偷袭的……这次是意外。', '这个……不合规矩。……可以再来一次。', '你吓了我一跳。那声尖叫，失礼了。'],
    ja: ['あっ——！……お早いお手つき。', 'くの一が不意を突かれるはずがないのに……今回だけ、特例。', 'それは……不躾です。……もう一度、どうぞ。', '驚いてしまいました。声が出たのは失礼。'],
  },
  marin: {
    en: ['Eeee! You DID it!', 'OMG that tickles, STOP— okay don\'t stop!', 'You\'re so bold~ I like it!', 'Poke wars: STARTED!'],
    yue: ['呀！！你真係敢喎！', 'OMG好痕呀，停——好喇唔准停！', '你咁大膽~我鍾意！', '戳戳大戰：正式開始！'],
    zh: ['呀！！你真敢呀！', 'OMG好痒啊，停——好啦不准停！', '你这么大胆~我喜欢！', '戳戳大战：正式开始！'],
    ja: ['きゃー！やったね！', 'OMGくすぐったい、やめて——やめないで！', '大胆だね〜好き！', 'つんつんウォーズ：開戦！'],
  },
  ayane: {
    en: ['…Hmph. Bold.', 'Touch me again and lose the hand. …Kidding. Probably.', 'You have a death wish. Cute.', 'Noted. You\'ll pay for that. Eventually.'],
    yue: ['……哼，好大膽。', '再掂我，隻手唔想要喇。……講笑啫，應該。', '你係咪活唔耐？幾可愛吖。', '記住喇。呢筆帳遲早同你算。'],
    zh: ['……哼，好大胆。', '再碰我，那只手不想要了。……开玩笑的，大概。', '你是不是活腻了？挺可爱的。', '记住了。这笔账迟早跟你算。'],
    ja: ['……ふん。大胆ね。', 'もう一度触ったら、その手はもらう。……冗談よ。たぶん。', '死にたいの？ふーん、かわいいところもあるじゃない。', '覚えておく。そのうち清算する。'],
  },
  hitomi: {
    en: ['Oh! Hehe — that tickles!', 'You\'re playful today! I like it.', 'Careful, I\'ll hug you for that.', 'Eek! Okay, fair — I\'d poke me too.'],
    yue: ['呀！嘻嘻——好痕呀！', '你今日好活潑吖！我鍾意。', '小心啲吖，我會攬返你㗎。', '吖！好吖，公道啲講，我都會戳我自己。'],
    zh: ['呀！嘻嘻——好痒呀！', '你今天好活泼呀！我喜欢。', '小心点哦，我会抱回来的。', '吖！好啦，公道地讲，我也会戳我自己。'],
    ja: ['あっ！ふふっ、くすぐったい！', '今日は元気だね！いいと思う。', '気をつけてね。お返しに抱きしめるよ。', 'ひゃっ！ふーん、私も自分ならつんつんしたい。'],
  },
  // ---- registry six (r2026-10-03.36) ----------------------------------------
  robbie: {
    en: ['Oi! Watch the hair, kid!', 'Haha! You got me!', 'Careful, I tickle back — big-bro style!', 'That\'s my little buddy — always full of surprises.'],
    yue: ['喂！小心個頭髮呀，細路！', '哈哈！俾你整親喇！', '小心啲，大哥會痕返你㗎！', '呢個就係我嘅細路——永遠咁多驚喜。'],
    zh: ['嘿！小心头发呀，小家伙！', '哈哈！被你整到了！', '小心点，大哥会挠回来的！', '这就是我的小家伙——永远这么多惊喜。'],
    ja: ['おい！髪に気をつけろ、ちびっ子！', 'ははっ！やられた！', '気をつけろ、お兄さんはかなり本気でくすぐり返すぞ！', 'うちのちびっ子はいつも意外性満点だな。'],
  },
  mika: {
    en: ['Whoa — offbeat, but I felt it.', 'Ha. You\'ve got rhythm.', 'Careful, you\'ll knock my guitar out of tune.', 'That\'s one way to get a musician\'s attention.'],
    yue: ['哇——甩咗拍，但我接到㗎。', '哈。你幾有節奏感喎。', '小心啲吖，會撞到我啱啱調好嘅音㗎。', '要引起音樂人注意，呢招都得。'],
    zh: ['哇——掉了拍子，但我接到了。', '哈。你挺有节奏感的。', '小心点呀，会撞到我刚调好的音的。', '要引起音乐人注意，这招也行。'],
    ja: ['おっと——拍子はずれたけど、受け取ったよ。', 'はっ。君、リズム感あるね。', '気をつけて、せっかく調律した音がずれちゃう。', 'ミュージシャンの注意を引くには、それも手だね。'],
  },
  anchor: {
    en: ['Steady on! You\'ll rock the boat.', 'Ha! Sharp as a squall, you are.', 'Mind yourself, sailor. That\'s mutiny.', 'A poke from you? I\'ve survived worse at sea.'],
    yue: ['企穩吖！你蕪到成隻船咁。', '哈！你犀利過海上暴風。', '小心啲吖水手，呢個係叛變㗎。', '俾你戳一下？我喺海上捱過更惡劣嘅。'],
    zh: ['站稳呀！你晃得整只船都在动。', '哈！你比海上风暴还犀利。', '小心点水手，这是叛变呀。', '被你戳一下？我在海上熬过更恶劣的。'],
    ja: ['しっかり掴まりな！船が揺れるだろう。', 'はっ！海上のスコールより鋭いな。', '気をつけろ水兵。これは反乱だぞ。', 'つんつんされたか？海ならもっと酷いのをくぐってきた。'],
  },
  lydia: {
    en: ['Darling! You\'ll wrinkle the couture.', 'Mmm. Bold. I approve.', 'Careful — I know three scandalous stories about you now.', 'That\'s how you get invited to everything, sweetheart.'],
    yue: ['親愛嘅！你會整皺件衫㗎。', '嗯。大膽。我批准。', '小心啲吖，而家我手上有你三個八卦㗎喇。', '呢啲就係點解你乜嘢派對都有份，心肝。'],
    zh: ['亲爱的！你会把衣服弄皱的。', '嗯。大胆。我批准。', '小心点呀，现在我手上有你的三个八卦了。', '这就是为什么你什么派对都有份，心肝。'],
    ja: ['ダーリン！服がしわになるじゃない。', 'ふーん。大胆。認めるわ。', '気をつけて。今のところあなたのスキャンダル話を三つ知ってるのよ。', 'それがどうしてあなたがどのパーティーにも呼ばれるのか、気の毒ね。'],
  },
  ruby: {
    en: ['Eee! You found my tickle spot!', 'Boing! That surprised my whole body!', 'Hey hey hey! Careful, I might bounce into you!', 'Hee hee! Do it again, do it again!'],
    yue: ['呀！你搵到我嘅痕位喇！', '彈！成身都俾你嚇親！', '喂喂喂！小心啲，我會彈返埋你度㗎！', '嘻嘻！再嚟一次再嚟一次！'],
    zh: ['呀！你找到我的痒位了！', '弹！全身都被你吓到了！', '喂喂喂！小心点，我会弹回去的！', '嘻嘻！再来一次再来一次！'],
    ja: ['きゃっ！くすぐりポイントを見つけちゃった！', 'ぴょん！びっくりして全身跳ねちゃった！', 'ちょちょちょ！気をつけて、跳ね返っちゃうよ！', 'うふふ！もう一度、もう一度！'],
  },
  snowy: {
    en: ['Eep! You melted my concentration!', 'Oh! Snowflakes scattered everywhere!', 'Careful… I might freeze you… with a hug!', 'Hee hee. That tickled like a snowball!'],
    yue: ['呀！你融咗我嘅專注力喇！', '哦！雪花散到周圍都係！', '小心啲吖……我會冰凍你㗎……用一個抱抱！', '嘻嘻。痕得似個雪球咁！'],
    zh: ['呀！你融化了我的专注力！', '哦！雪花散得到处都是！', '小心点呀……我会冰冻你的……用一个抱抱！', '嘻嘻。痒得像个雪球！'],
    ja: ['きゃっ！集中が溶けちゃった！', 'あっ！雪が散らばっちゃった！', '気をつけて……氷漬けにしちゃうよ……ハグで！', 'うふふ。雪玉みたいにくすぐったい！'],
  },
};

const FALLBACK_LANG: Lang = 'en';

/** Deterministic per-character idle line; falls back to the generic bank. */
export function pickIdleLine(characterId: string, lang: Lang, n: number): string {
  const bank = CHARACTER_IDLE[characterId]?.[lang] ?? CHARACTER_IDLE[characterId]?.[FALLBACK_LANG];
  if (bank?.length) return bank[((n % bank.length) + bank.length) % bank.length]!;
  return pickLine('idleBored', lang, n);
}

/** Deterministic per-character poke reaction; falls back to the generic bank. */
export function pickPokeLine(characterId: string, lang: Lang, n: number): string {
  const bank = CHARACTER_POKE[characterId]?.[lang] ?? CHARACTER_POKE[characterId]?.[FALLBACK_LANG];
  if (bank?.length) return bank[((n % bank.length) + bank.length) % bank.length]!;
  return pickLine('poke', lang, n);
}
