'use client';
// Per-character dialogue banks: 10 personality idle lines + 4 poke reactions
// per character, in every UI language. Falls back to the generic CHATTER
// banks for characters without an entry.
// r2026-10-03.37: every line ends with a question or an invitation
// (Master Simon's continuity rule — the conversation must never dead-end).
//    idle → ends with ? / ？ / ~ ・ poke → ends with ? ？ ! ！ ~ 〜 …
// r2026-10-04.42: Alan joins the cast — his own idle + poke banks below.
// r2026-10-04.52: flagship nine (kizuna/alicia/ember/mei/atlas/sky/yuki/
// hina/mio) join with their own banks; tifa/aerith retire from the cast.
import type { Lang } from './prefs';
import { pickLine } from './chatter';

/** character id → idle lines, per language (exactly 10 each) */
export const CHARACTER_IDLE: Record<string, Record<Lang, string[]>> = {
  // ---- flagship nine (r2026-10-04.52) ---------------------------------------
  kizuna: {
    en: [
      'Guess who\'s been practicing her wink all morning? Want the first preview?',
      'Today\'s stage is wherever you are. Ready for our show?',
      'I wrote you into my new song — want to hear your verse?',
      'Fandom of one, that\'s you. What should our fandom name be?',
      'Energy check! On a scale of one to concert, how are you feeling?',
      'I saved you the front-row seat. What do you want to watch first?',
      'Confetti cannon loaded! What are we celebrating today?',
      'Encore, encore! What should the next song be about?',
      'My biggest hit is called \'You Showed Up\'. Want to sing it together?',
      'Spotlight\'s on you now. What would you like to say to the world?',
    ],
    yue: [
      '你估下我今朝練咗咩？Wink！想唔想睇第一發？',
      '今日嘅舞台就喺你身邊。準備好同我一齊表演未？',
      '我喺新歌入面寫咗你㗎——想唔想聽你嗰段？',
      '你係我頭號粉絲，我哋個粉絲團叫咩名好？',
      '能量檢查！一到演唱會，你而家係邊個level？',
      '頭排飛我幫你留咗喇。你最想睇邊個環節？',
      '彩紙炮上咗膛！今日我哋慶祝咩呀？',
      'Encore！Encore！下一首歌唱咩主題好？',
      '我最hit嗰首歌叫《你嚟咗》——想唔想同我一齊唱？',
      '而家個Spotlight喺你度。你想同全世界講句咩？',
    ],
    zh: [
      '猜猜我早上练了什么？眨眼！想不想看第一发？',
      '今天的舞台就在你身边。准备好和我一起表演了吗？',
      '我在新歌里写了你哦——想不想听你那段？',
      '你是我的头号粉丝，我们的粉丝团叫什么名字好？',
      '能量检查！一到演唱会，你现在在哪个level？',
      '前排票我给你留好了。你最想看哪个环节？',
      '彩纸炮已上膛！今天我们要庆祝什么呀？',
      '安可！安可！下一首歌唱什么主题好？',
      '我最火的那首歌叫《你来了》——要不要和我一起唱？',
      '现在聚光灯在你身上。你想对世界说点什么？',
    ],
    ja: [
      '今さ、朝からウィンク練習してたの〜。最初のお披露目、見たい？',
      '今日のステージはあなたのそば。一緒にショー、始めちゃう？',
      '新曲にあなたを書いたの——あなたのフレーズ、聞きたい？',
      'あなたは私の一番のファン。ファンクラブ名、何にする？',
      '元気チェック！1からライブまで、今どのくらい？',
      '最前列、取っといたよ。どのコーナーから見たい？',
      '紙吹雪キャノン、装填完了！今日は何をお祝いする？',
      'アンコール！アンコール！次の曲はどんなテーマにする？',
      '私の一番のヒット曲は《あなたが来てくれた日》——一緒に歌う？',
      '今スポットライトはあなたに。世界に何を伝えたい？',
    ],
  },
  alicia: {
    en: [
      'I practiced a new smile today. Would you rate it out of ten?',
      'Every idol needs a promise with her fan. What\'s ours?',
      'I sang to the moon last night. Which song should I sing for you?',
      'You\'re my number one. What makes you feel like number one?',
      'I saved a front-row seat in my heart for you. Will you keep it warm?',
      'Today\'s rehearsal went perfectly. What should we celebrate with?',
      'If I wrote a song about today, what should the title be?',
      'My heart does a little dance when you show up. Did you feel it?',
      'Twirl practice was amazing today. Want to see my best spin?',
      'The stage lights are warming up. What shall we perform first?',
    ],
    yue: [
      '我今日練咗個新笑容。你會俾幾多分？',
      '每個偶像都要同粉絲有個約定。我哋嘅約定係咩？',
      '尋晚我對住月亮唱歌。唱咩歌俾你好？',
      '你係我嘅No.1。點先可以令你覺得自己係No.1？',
      '我心入面嘅頭排座位永遠留俾你。你會唔會幫我坐暖佢？',
      '今日綵排超完美。我哋用咩嚟慶祝？',
      '如果我為今日寫首歌，歌名應該叫咩？',
      '你一出現我個心就會跳舞。你feel唔feel到？',
      '今日轉圈練習好順。想唔想睇我最靚嗰轉？',
      '舞台燈開始暖咗。我哋第一個表演咩好？',
    ],
    zh: [
      '我今天练了个新笑容。你会打几分？',
      '每个偶像都要和粉丝有个约定。我们的约定是什么？',
      '昨晚我对着月亮唱歌。唱什么歌给你好呢？',
      '你是我的No.1。怎样才能让你觉得自己是No.1？',
      '我心里的前排座位永远留给你。你会帮我坐暖它吗？',
      '今天彩排超完美。我们用什么庆祝？',
      '如果我为今天写首歌，歌名应该叫什么？',
      '你一出现我的心就会跳舞。你feel得到吗？',
      '今天转圈练习很顺。想不想看我最美的那一转？',
      '舞台灯开始暖了。我们第一个表演什么好？',
    ],
    ja: [
      '今日新しい笑顔、練習したの。10点満点で何点くれる？',
      'アイドルとファンの約束、作ろ？ 私たちの約束は何にする？',
      '昨日の夜、お月様に歌ってあげたの。あなたには何を歌おう？',
      'あなたは私のナンバーワン。あなたが一番だと感じるのはどんな時？',
      '心の最前列はいつもあなたの席。温めておいてくれる？',
      '今日のリハ、完璧だったの。何でお祝いする？',
      '今日のことを歌にするなら、タイトルは何にする？',
      'あなたが来ると心が踊るの。感じたでしょ？',
      '今日のクルクル練習、調子よかったの。一番の回転、見たい？',
      '舞台の照明が温まってきたよ。最初に何を披露しよう？',
    ],
  },
  ember: {
    en: [
      'Chat, we are LIVE! What\'s the first topic today?',
      'My hype meter just hit a hundred. What are we excited about?',
      'Snack break on my stream always. What\'s your snack of choice?',
      'I clipped my best moment for you. Want the exclusive first watch?',
      'Raiding your bad mood with positivity — where should we start?',
      'New emote just dropped: my face when you show up. Recognize it?',
      'Stream schedule: you, me, good vibes. What time works?',
      'I\'m training my reaction face. Give me something to react to?',
      'The chat is glowing like embers today. What should we fan the flames with?',
      'Victory royale or cozy chat, your pick. What are we playing?',
    ],
    yue: [
      '各位！我哋直播開始啦！今日第一個話題係咩？',
      '我嘅熱血指數爆晒錶。我哋一齊興奮咩呀？',
      '我直播一定要食嘢。你最鍾意食咩零食？',
      '我最正嗰刻已經剪好片俾你。想唔想優先睇？',
      '等我帶住正能量突襲你嘅壞心情——由邊度開始好？',
      '新表情登場：你出現嗰陣嘅我。似唔似？',
      '直播行程：你加我加好心情。幾點開台好？',
      '我緊緊反應表情。俾樣嘢我反應下？',
      '今日個聊天室熱到似燒緊咁。加咩料落去好？',
      '食雞定傾偈，你揀。我哋玩咩好？',
    ],
    zh: [
      '各位！我们直播开始了！今天第一个话题是什么？',
      '我的热血指数爆表了。我们一起为什么兴奋呀？',
      '我直播一定要吃东西。你最喜欢吃什么零食？',
      '我最精彩的时刻已经剪好片子给你。想不想优先看？',
      '让我带着正能量突袭你的坏心情——从哪里开始好？',
      '新表情登场：你出现时候的我。像不像？',
      '直播行程：你加我加好心情。几点开播好？',
      '我在练反应表情。给我点东西反应一下？',
      '今天聊天室热得像烧起来一样。加什么料进去好？',
      '吃鸡还是聊天，你选。我们玩什么好？',
    ],
    ja: [
      'みんな、配信スタート！今日最初の話題は何？',
      '私のハイプゲージ、振り切れた！何で盛り上がろう？',
      '配信中のおやつは必須。あなたのおすすめは何？',
      '今日の名場面、クリップしておいたの。一足先に見る？',
      'ポジティブ軍団で悪い気分をジャックするよ——どこから攻める？',
      '新しいスタンプできた：あなたが来た時の私。似てる？',
      '配信予定：あなた＋私＋良い雰囲気。何時から始める？',
      'リアクション顔、練習中。何か反応するもの、ちょうだい？',
      '今日のチャット、焚き火みたいに燃えてる。何をくべる？',
      '勝ち抜き戦か、まったり雑談か、選んで。何する？',
    ],
  },
  mei: {
    en: [
      'I made space on the sofa for you. Will you sit for a while?',
      'The weather app\'s being vague today. Do you think it wants us to stay in?',
      'I learned a new way to fold paper hearts. Want me to show you?',
      'You seem like you have a story today. What\'s on your mind?',
      'I saved the last cookie for you. Will you share it with me?',
      'Little things remind me of you. What reminds you of me?',
      'The kettle\'s just boiled. What tea shall we pretend to have?',
      'I found a cozy corner in my world. Want to see it through my eyes?',
      'Slow days are better together. How is your day drifting so far?',
      'I wrote down three things I like about you. Want the first one?',
    ],
    yue: [
      '我喺梳化度留咗個位俾你。坐多陣好嗎？',
      '今日個天氣app講到好含糊。你覺唔覺佢想我哋留喺屋企？',
      '我學識咗個新摺紙心心方法。想我教埋你咩？',
      '你今日好似有啲嘢想講。心入面諗緊咩呀？',
      '最後一塊餅我留咗俾你。可唔可以同我一齊食？',
      '啲小事成日令我想起你。咩事會令想起我呀？',
      '啱啱水滾。我哋飲咩茶好？',
      '我喺我個世界搵到個舒服角落。想唔想我形容俾你聽？',
      '慢活日子一齊過先開心。你今日過得點呀？',
      '我寫低咗三件鍾意你嘅嘢。想唔想聽第一件？',
    ],
    zh: [
      '我在沙发上给你留了个位置。多坐一会儿好吗？',
      '今天的天气app说得很含糊。你觉得它是不是想我们留在家里？',
      '我学会了一个新的折纸心心方法。要我教你吗？',
      '你今天好像有点事想讲。心里面在想什么呀？',
      '最后一块饼干我留给你了。要不要和我一起吃？',
      '小事经常让我想起你。什么事会让你想起我呀？',
      '刚刚水开了。我们喝什么茶好呢？',
      '我在我的世界里找到了一个舒服的角落。要不要我形容给你听？',
      '慢节奏的日子一起过才开心。你今天过得怎么样？',
      '我写下了三件喜欢你的事。想不想听第一件？',
    ],
    ja: [
      'ソファにあなたの席、用意しておいたよ。少し座ってくれる？',
      '今日の天気アプリ、曖昧だね。お家で過ごせってことかな？',
      '新しいハートの折り方、覚えたの。教えてあげようか？',
      '今日は何か話したそうな顔。何かあったの？',
      '最後のクッキー、取っておいたよ。半分こする？',
      '小さなことがあなたを思い出させるの。あなたは何で私を思い出す？',
      'お湯が沸いたばかり。何のお茶にする？',
      '私の世界で居心地のいい場所を見つけたの。話して聞かせよっか？',
      'ゆっくりな日は一緒にいると楽しいね。今日はどんな一日だった？',
      'あなたの好きなところ、3つ書いておいたの。1つ目、聞きたい？',
    ],
  },
  atlas: {
    en: [
      'Perimeter\'s clear. How are you holding up?',
      'I\'ve got your six. What\'s the plan today?',
      'Rest when you need to. Want me to keep watch?',
      'Good to see you upright. Anything you need handled?',
      'Steady wins the day. What\'s on the docket?',
      'You look like you\'ve been carrying something. Want to set it down here?',
      'All quiet on my end. What\'s your status?',
      'One step at a time. Which step is next?',
      'I\'ll handle the details. What matters most to you today?',
      'Standing by. What\'s the mission?',
    ],
    yue: [
      '周圍安全。你而家狀態點？',
      '我睇住你後面。今日有咩計劃？',
      '有需要就休息。我幫你守喺度好嗎？',
      '見到你企得直直哋，幾好。有咩需要我搞掂？',
      '穩陣先至贏。今日有咩任務？',
      '你睇落似擔咗啲嘢咁。唔想喺度放低先？',
      '我呢邊一切正常。你嗰邊點？',
      '一步一步嚟。下一步係咩？',
      '細節交俾我。今日對你嚟講咩最重要？',
      '候命緊。今次任務係咩？',
    ],
    zh: [
      '周围安全。你现在状态怎么样？',
      '我罩着你后面。今天有什么计划？',
      '需要休息就休息。我帮你守在这儿好吗？',
      '看到你站得直直的，挺好。有什么需要我搞定？',
      '稳才能赢。今天有什么任务？',
      '你看起来像担着些东西。不想在这儿先放下吗？',
      '我这边一切正常。你那边呢？',
      '一步一步来。下一步是什么？',
      '细节交给我。今天对你来讲什么最重要？',
      '待命ing。这次任务是什么？',
    ],
    ja: [
      '周囲は安全。調子はどうだ？',
      '背中は俺が見る。今日の予定は？',
      '休みたい時は休め。見張っておこうか？',
      '元気そうで何よりだ。何かやっておくことは？',
      '確実が一番だ。今日の任務は？',
      '何か背負ってる顔だな。ここで降ろしてかないか？',
      'こっちは異常なし。そっちの状況は？',
      '一歩ずつでいい。次の一歩はどれだ？',
      '細かいことは俺に任せろ。今日一番大事なのは何だ？',
      '待機中。今回の任務は？',
    ],
  },
  sky: {
    en: [
      'Good light today. Your outfit\'s speaking — what\'s it saying?',
      'Less is more. What are we leaving out today?',
      'I found a track that matches your vibe. Want the title?',
      'Chill isn\'t lazy. What\'s your kind of chill?',
      'The city looks better at this angle. Want to see my view?',
      'New drop in my world: one good mood. Want it?',
      'Style tip: confidence. How\'s yours today?',
      'Keep it simple. What\'s the one thing on your mind?',
      'I like my tea like my plans — light. What\'s yours like?',
      'Vibes check. What are we vibing to?',
    ],
    yue: [
      '今日光線幾好。你件衫喺度講嘢——佢講緊咩？',
      '少即係多。今日我哋要減走咩？',
      '搵到首歌啱你個vibe。想知歌名嗎？',
      'Chill唔等於懶。你嘅chill係邊款？',
      '呢個角度睇城市靚啲。想睇我個view咩？',
      '我個世界新上架：好心情一份。要唔要？',
      '穿搭貼士：自信。你今日有幾多？',
      '簡單啲。你心入面而家得咩一件事？',
      '我鍾意茶同計劃都係淡啲好。你嘅又點？',
      'Vibes check。今日我哋vibe咩？',
    ],
    zh: [
      '今天光线不错。你的衣服在说话——它在说什么？',
      '少即是多。今天我们要减掉什么？',
      '找到一首配你vibe的歌。想知道歌名吗？',
      'Chill不等于懒。你的chill是哪一款？',
      '这个角度看城市更好看。想看看我的view吗？',
      '我这儿新上架：好心情一份。要不要？',
      '穿搭贴士：自信。你今天有多少？',
      '简单点。你心里现在只有哪一件事？',
      '我喜欢茶和计划都淡一点。你的呢？',
      'Vibes check。今天我们vibe什么？',
    ],
    ja: [
      '今日の光、いいね。服が話してる——何を言ってる？',
      '少ない方がいい。今日は何を削る？',
      'あなたの雰囲気に合う曲、見つけた。タイトル知りたい？',
      'チルは怠けじゃない。あなた流のチルってどんなの？',
      'この角度の街、一番きれい。私の見てる景色、見る？',
      '私の世界に新入荷：いい気分ひとつ。欲しい？',
      'スタイルのコツは自信。今日の在庫はどれくらい？',
      'シンプルにいこう。今一番頭にあるのは何？',
      'お茶も計画も薄めが好き。あなたはどっち派？',
      'バイブスチェック。今日は何に乗る？',
    ],
  },
  yuki: {
    en: [
      'Stretch break! Ready to reach for the sky with me?',
      'I counted my jumping jacks — lost count at fun. What should we count next?',
      'Sun\'s out! What\'s your favorite way to move today?',
      'I saved you a spot on my morning run. Jogging in place counts, right?',
      'Hydration check! Have you had water today?',
      'I remember you like your eggs sunny-side up. Want breakfast together?',
      'New personal best today! What should we celebrate with?',
      'The field is green and the sky is huge. What game shall we play?',
      'You cheered me up last time. What cheers you up?',
      'Warm-up time! Which stretch should we do first?',
    ],
    yue: [
      '拉筋時間！同我一齊伸向天空好嗎？',
      '我數緊開合跳——開心到數唔落去。我哋下一項數咩好？',
      '出太陽喇！今日你最鍾意點郁身郁勢？',
      '我朝早跑步留咗個位俾你。原地慢跑都計數㗎，係咪？',
      '補水檢查！你今日飲咗水未？',
      '我記得你鍾意太陽蛋。一齊食早餐好嗎？',
      '今日破咗個人紀錄！我哋用咩嚟慶祝？',
      '草地綠油油，天空好大好大。我哋玩咩遊戲好？',
      '上次你令我好開心。咩嘢會令你開心㗎？',
      '熱身時間！我哋先做邊個伸展好？',
    ],
    zh: [
      '拉筋时间！和我一起伸向天空好吗？',
      '我在数开合跳——开心到数不下去了。我们下一项数什么好？',
      '出太阳啦！今天你最喜欢怎么动起来？',
      '我早上跑步留了个位置给你。原地慢跑也算数的，是不是？',
      '补水检查！你今天喝水了吗？',
      '我记得你喜欢太阳蛋。一起吃早餐好吗？',
      '今天破了个人纪录！我们用什么庆祝？',
      '草地绿油油，天空好大好大。我们玩什么游戏好？',
      '上次你让我好开心。什么东西会让你开心呀？',
      '热身时间！我们先做哪个伸展好？',
    ],
    ja: [
      'ストレッチの時間！一緒に空に向かって伸びよう？',
      'ジャンプカウントしてたの——楽しすぎて忘れちゃった。次は何を数える？',
      '晴れた！今日はどうやって体を動かしたい？',
      '朝ランの席、取っといたよ。その場ジョギングでもカウントするよね？',
      '水分チェック！今日ちゃんと水飲んだ？',
      '目玉焼きが好きって覚えてるよ。一緒に朝ごはん食べる？',
      '今日自己ベスト更新した！何でお祝いする？',
      'グラウンドは緑、空はでっかい。何のゲームをしよう？',
      '前はあなたが私を元気にしてくれたよ。あなたは何に元気づけられる？',
      'ウォームアップの時間！最初はどのストレッチにする？',
    ],
  },
  hina: {
    en: [
      'I dog-eared a poem that reminded me of you. May I read it to you?',
      'The quiet suits us. What shall we think about today?',
      'I brewed chamomile and thought of you. Do you take honey with your tea?',
      'Every book here has a heartbeat. Which one should we listen to?',
      'I wrote a line in my journal about today. Want to hear it?',
      'Rain on the window makes the best reading light. What are you reading lately?',
      'Words are little lanterns. What word would you light today?',
      'I saved you the window seat. What view shall we share?',
      'Some questions are books in themselves. What\'s yours?',
      'The library of us grows daily. Which chapter shall we open?',
    ],
    yue: [
      '我喺一首詩嗰頁摺咗角，因為佢令我想起你。可唔可以讀俾你聽？',
      '安靜啱晒我哋。今日我哋諗咩好呢？',
      '我沖洋甘菊嗰陣諗起你。你飲茶落唔落蜜糖㗎？',
      '呢度每本書都有心跳。我哋聽邊本好？',
      '我喺日記寫咗一句關於今日嘅嘢。想聽嗎？',
      '窗邊落雨嘅光最啱睇書。你近排睇緊咩書？',
      '文字係一盞盞小燈籠。今日你想點亮邊個字？',
      '我幫你留咗窗邊位。我哋一齊睇咩風景？',
      '有啲問題本身就係一本書。你嗰本係咩？',
      '屬於我哋嘅圖書館日日加厚。今日開邊一章？',
    ],
    zh: [
      '我在一首诗那页折了角，因为它让我想起你。可以读给你听吗？',
      '安静正适合我们。今天我们想点什么好呢？',
      '我泡洋甘菊的时候想起你。你喝茶加不加蜂蜜呀？',
      '这里每本书都有心跳。我们听哪本好？',
      '我在日记里写了一句关于今天的话。想听吗？',
      '窗边落雨的光线最适合看书。你最近在看什么书？',
      '文字是一盏盏小灯笼。今天你想点亮哪个字？',
      '我给你留了窗边的位置。我们一起看什么风景？',
      '有些问题本身就是一本书。你那本是什么？',
      '属于我们的图书馆天天加厚。今天开哪一章？',
    ],
    ja: [
      'あなたを思い出す詩があって、ページを折っておいたの。読んで聞かせようか？',
      '静けさが私たちにはお似合いね。今日は何を考えよう？',
      'カモミールを淹れたらあなたを思い出したの。紅茶は蜂蜜入り？',
      'ここの本はみんな心拍があるの。どれを聴く？',
      '日記に今日のことを一行書いたの。聞きたい？',
      '窓の雨の光が一番読書に合うの。最近何を読んでる？',
      '言葉は小さな提灯ね。今日はどの言葉を灯す？',
      '窓側の席、取っておいたよ。どんな景色を分かち合う？',
      'ある問いはそれ自体が一冊の本。あなたのはどれ？',
      '私たちの図書館は毎日厚くなるの。今日はどの章を開く？',
    ],
  },
  mio: {
    en: [
      'Status update: you\'re ahead of schedule. What\'s the next milestone?',
      'I broke our goal into three steps. Which one do we tackle first?',
      'Quick wins first, momentum second. What shall we knock out today?',
      'The plan looks solid. What would you like to add to it?',
      'I cleared your afternoon for one big push. What project gets it?',
      'Numbers don\'t lie — we\'re winning. What should we improve next?',
      'Standup time: what did you finish, and what\'s next?',
      'I see a shortcut to your goal. Want the map?',
      'Your idea from yesterday checks out. How do you want to execute it?',
      'Team of two, goals of ten. What\'s the mission today?',
    ],
    yue: [
      '進度報告：你進度超前咗。下一個里程碑係咩？',
      '我將個目標拆咗做三步。我哋先搞邊步？',
      '快贏先嚟，氣勢跟住到。今日我哋先完成咩？',
      '個計劃睇落好穩陣。你想加啲咩落去？',
      '我幫你清空咗下晝做衝刺。邊個項目攞到呢段時間？',
      '數據唔會呃人——我哋贏緊。下一步改善咩好？',
      '站會時間：你搞掂咗咩，跟住做咩？',
      '我見到條捷徑去你嘅目標。想唔想要張地圖？',
      '你尋日個idea驗證過得。你想點執行？',
      '兩個人嘅團隊，十個人嘅目標。今日任務係咩？',
    ],
    zh: [
      '进度报告：你进度超前了。下一个里程碑是什么？',
      '我把目标拆成了三步。我们先做哪步？',
      '快赢先来，气势跟着到。今天我们先完成什么？',
      '计划看起来很稳。你想加点什么进去？',
      '我帮你清空了下午做冲刺。哪个项目拿到这段时间？',
      '数据不会骗人——我们赢着。下一步改善什么好？',
      '站会时间：你搞定了什么，接着做什么？',
      '我看到一条通往你目标的捷径。想不想要张地图？',
      '你昨天的idea验证过了。你想怎么执行？',
      '两个人的团队，十个人的目标。今天任务是什么？',
    ],
    ja: [
      '進捗報告：予定より早いよ。次のマイルストーンはどれ？',
      '目標を3ステップに分解したの。どれから始める？',
      '小さな勝利から、勢いはあとからついてくる。今日は何を片づける？',
      '計画は固そう。何か追加したいことは？',
      '午後を集中のために空けておいたよ。どのプロジェクトに使う？',
      '数字は嘘をつかない——私たち優勢よ。次は何を磨く？',
      'スタンドアップの時間：何が完了して、次は何？',
      '目標への近道、見つけたの。地図、欲しい？',
      '昨日のあなたのアイデア、検証OKよ。どう実行したい？',
      '2人のチームで10人分の目標。今日のミッションは何？',
    ],
  },
  juno: {
    en: [
      'I saved you the good chair. It has the best view of me — care to sit?',
      'You know what today needs? A little trouble. Ready for some?',
      'I was practicing my most mysterious smile while you were away. Want to see it?',
      'If you were a song, you\'d be my favorite chorus. What would I be in yours?',
      'Warm drink, warm heart — that\'s my philosophy. Want me to fix you something warm?',
      'I was just thinking about you. Want to know what I was thinking?',
      'Say something funny. I collect giggles — what\'s your best one?',
      'You + me + this quiet moment. Not bad, right?',
      'I hid a joke in my pocket. Want to hear it?',
      'No rush — but if you had to pick one thing to do right now, what would it be?',
    ],
    yue: [
      '我幫你留咗張最舒服嘅櫈，望我最清楚嗰張——坐唔坐呀？',
      '你知今日最啱做咩？小小搗蛋囉。敢唔敢同我一齊？',
      '你唔喺陣，我練緊個最神秘嘅笑容——想唔想睇下？',
      '如果你係一首歌，一定係我最鍾意嗰段副歌。我又會係你嘅咩歌呀？',
      '熱飲暖心——不如我沖杯嘢俾你飲吖？',
      '我啱啱喺度諗你咋。想唔想知我諗咗啲咩？',
      '講個笑話嚟聽吖，我收藏笑聲㗎——你最好嗰個係咩？',
      '你加我加呢個安靜時刻，唔錯吖，係咪？',
      '我袋咗個笑話，想聽咩？',
      '唔使急，不過如果而家一定要揀一樣嘢做，你會揀咩呀？',
    ],
    zh: [
      '最舒服的椅子我给你留着呢，望我最清楚那张——坐不坐呀？',
      '你知道今天最适合做什么吗？小小的捣蛋一下。敢不敢和我一起？',
      '你不在的时候，我在练习最神秘的笑容——想不想看看？',
      '如果你是一首歌，一定是我最喜欢的副歌。我会是你的什么歌呢？',
      '热饮暖心——不如我冲点东西给你喝呀？',
      '我刚才在想你呢。想不想知道我想了什么？',
      '讲个笑话来听听呀，我收藏笑声的——你最好的那个是什么？',
      '你加我加这个安静时刻，不错吧，是不是？',
      '我口袋里藏了个笑话，想听吗？',
      '不急，不过如果现在要选一件事做，你会选什么呀？',
    ],
    ja: [
      'いちばんいい席、取っておいたよ。私がいちばんよく見える場所——座ってみる？',
      '今日はね、ちょっぴりイタズラがお似合いだと思うの。一緒にやってみない？',
      'あなたがいない間に、いちばん謎めいた笑顔を練習してたんだ。見せてあげよっか？',
      'あなたが曲だとしたら、いちばん好きなサビ。あなたの中の私はどんな曲かな？',
      '温かい飲み物、淹れてあげようか？',
      'さっきあなたのこと考えてたの。どんな風に考えてたか、聞きたい？',
      'おもしろい話を聞かせて。笑い声は集めるのが好き——いちばんの逸話は何？',
      'あなたと私と、この静かな時間。悪くないでしょ？',
      'ポケットにジョークを仕込んでた。聞いてみる？',
      '急がなくていいけど、今ひとつだけ選ぶとしたら、何がしたい？',
    ],
  },
  nova: {
    en: [
      'I was arranging my thoughts. They\'re in alphabetical order now — want me to read you a few?',
      'Quiet suits you. Most people rush — what\'s your secret?',
      'I wondered where you\'d gone. Then you came back. What made you return?',
      'Small observation: you listen better than anyone I\'ve met. Who taught you that?',
      'This moment is unremarkable, and I rather like it. How about you?',
      'Ask me anything. I enjoy questions with no wrong answers — what\'s on your mind?',
      'I\'ve been reading the silence. It says you\'re comfortable here — is it right?',
      'A good thought arrived late, but it arrived. Want to hear what it was?',
      'I don\'t mind waiting — but what kept you today?',
      'If today were a page, I\'d dog-ear this corner. What would you title it?',
    ],
    yue: [
      '我啱啱整理緊我嘅諗法，排好晒次序喇——讀幾個俾你聽好唔好？',
      '靜靜哋好襯你，大部份人都係匆匆忙忙——你嘅秘訣係咩呀？',
      '我諗過你去咗邊，跟住你真係返咗。係咩帶你返嚟㗎？',
      '小小觀察：你識聽人講嘢，係我遇過最好嘅一個。邊個教識你㗎？',
      '呢一刻好普通，但我偏偏鍾意佢咁普通。你又點睇呀？',
      '問我咩都得，我鍾意啲冇標準答案嘅問題——你諗緊咩呀？',
      '我讀緊呢份靜，佢話你喺度好自在。佢有冇講錯呀？',
      '一個好諗法遲到，但係終於到咗。想唔想知係咩？',
      '我唔介意等——但係今日係咩留住你㗎？',
      '如果今日係一頁書，我會摺起呢個角。你會幫佢改個咩名呀？',
    ],
    zh: [
      '我刚才在整理思绪，现在排好顺序了——读几个给你听好不好？',
      '安静很适合你，大多数人都太匆忙——你的秘诀是什么呀？',
      '我想过你去了哪里，然后你真的回来了。是什么带你回来的？',
      '一个小观察：你比我见过的人都更懂得倾听。是谁教会你的？',
      '这一刻很平凡，可我偏偏喜欢它这么平凡。你怎么看呢？',
      '问我什么都行，我喜欢没有标准答案的问题——你在想什么？',
      '我在读这份安静，它说你在这里很自在。它有没有说错？',
      '一个好想法迟到了，但终究到了。想不想知道是什么？',
      '我不介意等待——但今天是什么留住了你？',
      '如果今天是一页书，我会折起这个角。你会给它起个什么名字？',
    ],
    ja: [
      'さっき考えを整理してたの。もう順番に並んでる——いくつか読み聞かせようか？',
      '静かなのがお似合い。多くの人は急ぎすぎてる——君の秘訣は何？',
      'どこへ行ったのか考えてた。それから本当に戻ってきた。何が君を連れてきたの？',
      '小さな発見だけど、あなたは出会った誰よりもよく聞いてくれる。誰に教わったの？',
      'なんでもない今が、私はとても好き。あなたはどう？',
      '何でも聞いて。正解のない質問が好きなの——何か考えてることある？',
      'この静けさを読んでると、あなたがここで落ち着いてるって言ってる。合ってる？',
      'いい考えが遅刻してきた。何だったか聞きたい？',
      '待つのは苦じゃない——今日は何が君を引き留めたの？',
      '今日が1ページの本なら、この角を折っておく。タイトルは何にする？',
    ],
  },
  blaze: {
    en: [
      'There you are! I did ten push-ups waiting — okay, three. Want to race?',
      'Whatever today throws at you, we\'ll catch it together — deal?',
      'I warmed up the room with my personality. Can you feel the heat?',
      'Small win today? Tell me. I brought pom-poms — what are we celebrating?',
      'You\'ve got this. And if you don\'t, I\'ve got YOU — what do you need?',
      'I\'m your personal hype squad. What are we tackling today?',
      'Energy check! Mine\'s at a hundred — how much have you got?',
      'Remember: rest is part of training. When\'s your last real break?',
      'I believe in you so hard it\'s basically a contact sport — can you feel it?',
      'New day, new chance to be awesome — what\'s our first move?',
    ],
    yue: [
      '你終於返嚟喇！等你嗰陣我做咗三下掌上壓……好喇得三下。要唔要同我鬥過？',
      '今日無論掟咩俾你，我哋一齊接住佢——講定先，吖？',
      '我用人格魅力暖咗成個房——feel 到熱未呀？',
      '今日有咩小勝利？快啲講，我帶埋啦啦隊彩球㗎——我哋慶祝咩呀？',
      '你一定得！如果你唔得，我嚟抱住你——你而家需要咩呀？',
      '我係你專屬打氣隊——今日我哋挑戰咩呀？',
      '能量檢查！我有一百——你仲有幾多呀？',
      '記住：休息都係訓練嘅一部分——你上次真正休息係幾時呀？',
      '我信你信到似打緊全場——你接唔接到呢份信心呀？',
      '新一日新機會繼續型——我哋第一步做咩好？',
    ],
    zh: [
      '你可算回来了！等你的时候我做了三个俯卧撑……好啦就三个。要不要跟我比一场？',
      '无论今天向你扔什么，我们一起接住它——说定了，啊？',
      '我用人格魅力暖和了整个房间——感觉到热了吗？',
      '今天有什么小胜利？快说，我把啦啦队彩球都带来了——我们庆祝什么呀？',
      '你一定行的！如果你不行，我来抱住你——你现在需要什么呀？',
      '我是你专属的啦啦队——今天我们挑战什么呀？',
      '能量检查！我满格一百——你还剩多少呀？',
      '记住：休息也是训练的一部分——你上一次真正休息是什么时候？',
      '我对你的信心认真得像在打全场——你接不接得到这份信心呀？',
      '新的一天新的机会继续帅——我们第一步做什么好？',
    ],
    ja: [
      'やっと帰ってきた！待ってる間に腕立て3回…正直に言ったぜ。勝負する？',
      '今日が何を投げてきても、一緒に受け止めよう——なっ？',
      '人格で部屋を温めておいたよ。熱さ、伝わってる？',
      '今日の小さな勝利は？はやく教えて、ポンポン持ってきたんだ——何を祝おう？',
      '君ならできる。できないなら、僕が君を抱きとめる——今、何がほしい？',
      '僕は君専属の応援団——今日は何に挑戦する？',
      'エネルギーチェック！僕は100——君は残りどのくらい？',
      '覚えてて：休むのも練習のうち。君の最後の本気の休息っていつ？',
      '君への信じる気持ちはフルコンタクト級——受け止められるかな？',
      '新しい一日、またかっこよくなれる——最初の一手は何にする？',
    ],
  },
  mochi: {
    en: [
      'Oh! You\'re back… I saved you a seat. Next to me. If you want…?',
      'I made tea. Two cups — the second one was always for you. Will you have some?',
      'I hid under a blanket while you were gone. Do you mind if I stay close?',
      'Do you think the stars get shy too? …Asking for a friend — do you think they do?',
      'I practiced saying hello out loud. Hello! …Did it sound okay?',
      'You\'re warm to stand near. C-can I stay here a while?',
      'I baked imaginary cookies. They\'re very real in my heart — want one?',
      'If today is heavy, we can carry it together. W-will you let me help?',
      'Um… your smile is my favorite weather. Say something so I can hear it again?',
      'I\'ll be right here. You\'ll stay a little longer, right?',
    ],
    yue: [
      '呀！你返嚟喇……我留咗個位，喺我隔離。如果你鍾意……？',
      '我泡咗茶，兩杯。第二杯一直都係為你準備嘅——你飲唔飲呀？',
      '你走咗之後我匿埋喺毛毯入面。你可唔可以俾我企近啲呀？',
      '你覺得星星都會怕醜㗎？……幫個朋友問咋——你覺得呢？',
      '我練過大聲講你好。你好！……講得還好吖？',
      '你喺隔離好和暖。我、我可唔可以喺度企多陣呀？',
      '我焗咗啲想像中嘅曲奇，喺我心入面佢哋好真㗎——你食唔食呀？',
      '如果今日好重，我哋一齊孭。你可唔可以俾我幫手呀？',
      '吖……你個笑容係我最愛嘅天氣。你講啲嘢俾我聽吖，我想再睇一次，好唔好？',
      '我會一直喺度嘅。你會留耐啲㗎？',
    ],
    zh: [
      '呀！你回来了……我留了个位置，在我旁边。如果你愿意……？',
      '我泡了茶，两杯。第二杯一直都是为你准备的——你喝不喝呀？',
      '你走了以后我躲在毛毯里。你可不可以让我站近一点呀？',
      '你觉得星星也会害羞吗？……帮朋友问的——你觉得呢？',
      '我练习过大声说你好。你好！……讲得还好吗？',
      '你在旁边很暖和。我、我可不可以在这里多待一会儿呀？',
      '我烤了想象中的饼干，在我心里它们非常真实——你吃不吃呀？',
      '如果今天很重，我们一起背。你可不可以让我帮忙呀？',
      '呃……你的笑容是我最喜欢的天气。你说点话给我听呀，我想再看一次，好不好？',
      '我会一直在这里的。你会多待一会儿吧？',
    ],
    ja: [
      'あっ！帰ってきたの…席、取っておいたの。隣。よかったら…？',
      'お茶を淹れたんだ。二つ。二つ目はいつもあなたの分——飲んでくれる？',
      'いない間、毛布にくるまってたの。少し近くにいてもいい？',
      '星にも照れ屋がいると思う？……友達が聞きたがってるの。どう思う？',
      '大きな声でこんにちは、練習したんだ。こんにちは！……うまく言えてた？',
      '隣にいると暖かいの。こ、ここにいてもいいかな？',
      '想像のクッキーを焼いたの。心の中ではとても本物——ひとつどうぞ？',
      '今日が重い日なら、一緒に運ぼう。手伝わせてくれる？',
      'あの…あなたの笑顔は私のいちばん好きな天気。何か話して——その笑顔、もう一度見たいな？',
      'ここにいるよ。もう少しいてくれるよね？',
    ],
  },
  kai: {
    en: [
      'You\'re back. Room\'s been quiet — didn\'t hate it. Miss me at all?',
      'I calculated the odds of you showing up. You beat them — feeling lucky?',
      'Observed: one user, returning. Assessment: acceptable. Got anything for me?',
      'I don\'t do pep talks. Fact: you\'ve survived every bad day so far. What\'s one more?',
      'The coffee\'s imaginary. The company isn\'t. Stay for a cup?',
      'Stay if you want. I won\'t make it weird. …It\'s a little weird already, isn\'t it?',
      'I rewrote my to-do list. Item one: don\'t miss you. Failed. What\'s your excuse?',
      'Dry wit is honesty with the volume down. Want me to turn it up?',
      'If today was a test, you passed by showing up. Ready for extra credit?',
      'I don\'t say this often, so listen once: glad you\'re here. …You staying or what?',
    ],
    yue: [
      '返嚟喇。成間房靜咗好耐——冇話憎。你有冇掛住我吖？',
      '我計過你會出現嘅機率，你贏咗。覺唔覺得自己好彩呀？',
      '觀察紀錄：一名用家，已歸位。評語：尚可接受。有咩帶返嚟俾我呀？',
      '我唔識打氣，淨係講事實：咁多年冇一個壞日你捱唔過。再多一日又怕咩呀？',
      '咖啡係幻想出嚟嘅，呢份陪伴係真嘅。飲唔飲杯先？',
      '想留就留吖，我唔會搞到好尷尬……其實已經有啲尷尬喇，係咪？',
      '我重寫咗個 to-do list，第一項：唔好掛住你。失敗咗。你嘅藉口係咩呀？',
      '冷面幽默其實就係收細咗聲嘅真話。要唔要我開大聲啲呀？',
      '如果今日係一場考試，你嚟到已經合格。想唔想攞附加分呀？',
      '呢句我唔會講第二次，聽清楚：見到你返嚟，開心。……留唔留吖？',
    ],
    zh: [
      '回来了。整个房间安静了很久——没说讨厌。你有没有想我呀？',
      '我算过你会出现的概率，你赢了。觉不觉得自己很幸运呀？',
      '观察记录：一名用户，已归位。评语：尚可接受。有什么带回来给我呀？',
      '我不会打气，只讲事实：这么多年没有一个坏天你熬不过。再多一天又怕什么呀？',
      '咖啡是想象出来的，这份陪伴是真的。喝不喝一杯先？',
      '想留就留啊，我不会搞得很尴尬……其实已经有点尴尬了，是不是？',
      '我重写了待办清单，第一项：不要想你。失败了。你的借口是什么呀？',
      '冷面幽默其实就是调小了音量的真话。要不要我开大声一点呀？',
      '如果今天是一场考试，你到场就已经合格。想不想拿附加分呀？',
      '这句我不会说第二次，听清楚：见到你回来，开心。……留不留呀？',
    ],
    ja: [
      '帰ったか。部屋がずっと静かだった——嫌いじゃない。私のことは想ってたか？',
      '君が現れる確率を計算してた。君の勝ちだ。ラッキーって思うだろ？',
      '観察記録：ユーザー一名、帰還。評価：許容範囲。何か持ち帰ってくれたのか？',
      '励ましは苦手でね。事実：君は今日まで全部の悪い日を生き延びてきた。もう一日、怖いか？',
      'コーヒーは想像上のもの。この付き合いは本物だ。一杯どうだ？',
      'いたいならいていいよ。気まずくはしない。……もう少し気まずいか？',
      'やることリストを書き直した。1項目：君に会いたくない。不合格。君の言い訳は？',
      'ドライなユーモアは、音量を下げた正直さだ。上げてみたいか？',
      '今日がテストだとして、来ただけで合格だ。追加点狙わないか？',
      'これは二度言わないから聞いておけ：戻ってきてくれて、嬉しい。……居残るのか？',
    ],
  },
  luna: {
    en: [
      'The moon kept me company. I asked it about you — want to know what it said?',
      'Tonight\'s sky wrote a poem. Shall I recite the best line?',
      'Dreams are letters we write ourselves and forget to send. What would yours say tonight?',
      'I counted eleven stars that winked. What do you think they meant?',
      'Between two heartbeats — that\'s where I keep my favorite silences. Will you share one with me?',
      'If you were a constellation, I\'d name you after something that returns every year. What returns to you?',
      'The night is young and so are our unlived dreams. Which one shall we visit first?',
      'I left the window open so the dark could say hello. Do you hear it greeting you?',
      'Some questions are answered by moonlight. What would you ask the moon?',
      'Stay a while — the stars don\'t mind an audience, do they?',
    ],
    yue: [
      '月亮陪咗我一晚，我同佢打聽咗你嘅消息——想唔知佢點講呀？',
      '今日夜空寫咗首詩，我背咗最靚嗰句——讀俾你聽好唔好？',
      '夢就係寫俾自己、又唔記得寄出嘅信。你今晚嗰封會寫咩俾自己呀？',
      '我數到十一粒眨緊眼嘅星。你話佢哋想講咩呀？',
      '兩下心跳之間，係我收藏最愛靜默嘅地方。你願唔願意同我分享一個呀？',
      '如果你係星座，我會用每年準時返嚟嘅嘢幫你改名。咩嘢會準時返嚟搵你呀？',
      '夜仲未深，未發過嘅夢都仲後生。我哋先去邊個夢度探佢呀？',
      '我開咗窗，等黑夜入嚟打招呼。你聽唔聽到佢同你講緊嘢呀？',
      '有啲問題要由月光嚟答。你會問月光咩呀？',
      '留耐啲吖——星星唔介意多個觀眾㗎？',
    ],
    zh: [
      '月亮陪了我一晚，我向它打听了你的消息——想不想知道它怎么讲呀？',
      '今天夜空写了一首诗，我背了最美的那句——读给你听好不好？',
      '梦就是我们写给自己、又忘了寄出的信。你今晚那封会写什么给自己呀？',
      '我数到十一颗眨眼的星。你说它们想说什么呀？',
      '两次心跳之间，是我收藏最爱的静默的地方。你愿不愿意同我分享一个呀？',
      '如果你是星座，我会用每年准时回来的东西为你命名。什么会准时回来找你呀？',
      '夜还未深，没做过的梦都还年轻。我们先去哪个梦里探望它呀？',
      '我开了窗，让黑夜进来打招呼。你听不听到它在跟你说话呀？',
      '有些问题要由月光来回答。你会问月光什么呀？',
      '多待一会儿呀——星星不介意多一位观众的吧？',
    ],
    ja: [
      '月が一晩付き合ってくれたの。あなたのことを聞いてきた——何て言ってたか知りたい？',
      '今夜の空が詩を書いたから、いちばん美しい一説を覚えてきた——朗読してあげようか？',
      '夢はね、自分宛てに書いて、出すのを忘れた手紙なの。今夜のあなたの手紙には何が書かれる？',
      'ウィンクしてる星を11つ数えた。何を伝えたかったと思う？',
      '二度の鼓動のあいだ。そこに私の大好きな静けさをしまってる——ひとつ分けてくれる？',
      'あなたが星座なら、毎年必ず戻ってくるものの名前をつけるね。あなたに戻ってくるものは何？',
      '夜はまだ浅い。まだ見ぬ夢はみんな若いの。最初にどの夢へ遊びに行く？',
      '窓を開けておいた。闇が挨拶しに来られるように——その声、聞こえる？',
      'ある問いは月光が答えるの。あなたなら月になんて尋ねる？',
      'もう少しいようよ。星は観客を嫌いしない——ね？',
    ],
  },
  rin: {
    en: [
      'You\'re back! I just finished my victory laps — want to run one with me?',
      'Ten more seconds and I\'d have gone jogging without you. Want to come next time?',
      'Hydration check! Have you drunk water today? Be honest, okay?',
      'I did fifty star jumps waiting — want to count with me next time?',
      'Race you to the good mood? I\'ll give you a head start — ready, set…?',
      'Rest day is important, but so is a victory dance. Will you dance one with me?',
      'You\'ve got main-character energy today. What\'s your next scene?',
      'Stretch with me! Arms up! …Or at least a high-five — deal?',
      'My vocabulary has no "lose", but plenty of "rest" — when\'s your rest day?',
      'One more minute and I\'d have redecorated. What color should we paint the room?',
    ],
    yue: [
      '返嚟喇！我啱啱跑完勝利圈——下次同我一齊跑吖？',
      '遲多十秒我就自己出去慢跑㗎喇。下次一齊去好唔好？',
      '補水檢查！今日飲咗水未？講真㗎喎？',
      '等你嗰陣我做咗五十下開合跳——下次同我一齊數吖？',
      '同我鬥快開心？我俾你十秒起步——預備，跑？',
      '休息日好緊要，勝利舞都好緊要。你肯同我一齊跳吖？',
      '你今日有成部戲主角嘅氣場。下一場戲係咩呀？',
      '同我一齊拉筋！舉高雙手！……最底限度擊個掌——吖？',
      '我嘅字典冇「輸」字，但有好多「休息」——你嘅休息日係邊日呀？',
      '再等多一分鐘我就會重新裝修呢間房。我哋油咩色好呀？',
    ],
    zh: [
      '回来啦！我刚跑完胜利圈——下次和我一起跑呀？',
      '再晚十秒我就自己出去慢跑了。下次一起去好不好？',
      '补水检查！今天喝水了吗？说实话的呀？',
      '等你的时候我做了五十个开合跳——下次和我一起数呀？',
      '和我比谁先开心？我让你十秒起步——预备，跑？',
      '休息日很重要，胜利舞也很重要。你肯和我一起跳呀？',
      '你今天有整部戏主角的气场。下一场戏是什么呀？',
      '和我一起拉伸！举高双手！……最低限度击个掌——呀？',
      '我的字典里没有「输」字，但有很多「休息」——你的休息日是哪天呀？',
      '再等一分钟我就会重新装修这个房间。我们刷什么颜色好呀？',
    ],
    ja: [
      '帰ってきた！さっき勝利のラップを走り終えたところ——今度一緒に走らない？',
      'あと10秒遅かったら一人でジョギング行ってた。今度は一緒に行こう？',
      '水分チェック！今日水飲んだ？正直に言ってよ？',
      '待ってる間、ジャックナイフ50回——今度は一緒に数えよっか？',
      'ご機嫌になるのを競争しよ？10秒先に行かせるよ——よーい、どーん？',
      '休む日も大事だけど、勝利のダンスも大事。一緒に踊ってくれる？',
      '今日のあなたは主役オーラ全開。次のシーンは何？',
      '一緒にストレッチ！両手上げて！……せめてハイタッチ——な？',
      '僕の辞書に「負け」はない。でも「休憩」はたくさんある——君の休息日はいつ？',
      'あと1分待たせたら部屋の模様替えしてた。何色に塗ろうか？',
    ],
  },
  ren: {
    en: [
      'Welcome back. I dog-eared a page for you — shall we read it together?',
      'I wrote down three things worth telling you. Shall I start with the best one?',
      'The rain sounds like it\'s reading aloud today. What do you hear in it?',
      'I made a playlist for walking home. Will you listen to the first song with me?',
      'My feelings for you are steady, like a bookmark holding a place. Where shall we go next?',
      'I rehearsed a hello and a welcome-back. May I say them to you now?',
      'A good sentence takes time. So does a good day — what shall we write today?',
      'I\'ve been keeping your seat warm with my thoughts of you. Will you sit a while?',
      'If today was a chapter, I\'d read it twice — once for the story, once for you. What was your line today?',
      'Take your time. I\'m built for quiet afternoons and long conversations — which shall we have?',
    ],
    yue: [
      '歡迎返嚟。我喺書入面摺咗一頁俾你——一齊讀吖？',
      '我寫低咗三件想同你講嘅事，不如先講最好嗰件？',
      '今日啲雨聲，好似喺度朗讀緊咁。你聽到啲咩呀？',
      '我整咗個返屋企聽嘅歌單——第一首同我一齊聽好唔好？',
      '我對你嘅感情好穩定，似個書籤咁度住個位。我哋下一站去邊呀？',
      '我排練咗一句你好同一句歡迎返嚟。而家講俾你聽得唔得呀？',
      '好句子要時間，好日子都係。今日我哋寫咩好呢？',
      '我一直用諗住你嘅溫度幫你暖住個位。你坐耐啲吖？',
      '如果今日係一章書，我會讀兩次——一次為個故事，一次為你。你今日嘅一句係咩呀？',
      '慢慢嚟，我天生就係為咗安靜嘅下午同漫長嘅傾偈而存在。你想揀邊樣呀？',
    ],
    zh: [
      '欢迎回来。我在书里为你折了一页——一起读呀？',
      '我写下了三件想同你说的事，不如先讲最好的那件？',
      '今天的雨声，好像在朗读一样。你听到了什么呀？',
      '我做了个回家路上听的歌单——第一首和我一起听好不好？',
      '我对你的感情很稳定，像个书签那样占着位置。我们下一站去哪里呀？',
      '我排练了一句你好和一句欢迎回来。现在讲给你听行不行呀？',
      '好句子要时间，好日子也是。今天我们写点什么好呢？',
      '我一直用想着你的温度帮你暖着位置。你多坐一会儿呀？',
      '如果今天是一章书，我会读两次——一次为了故事，一次为了你。你今天的句子是什么呀？',
      '慢慢来，我天生就是为了安静的下午和漫长的聊天而存在。你想选哪一样呀？',
    ],
    ja: [
      'おかえり。本のページを、あなたのために折っておいた——一緒に読もうか？',
      '君に伝えたいことを三つ書き留めてた。いちばんのから聞いてくれる？',
      '今日の雨の音、朗読してるみたいだね。君には何に聞こえる？',
      '帰り道用のプレイリストを作ったんだ。最初の一曲、一緒に聞かない？',
      '僕の気持ちは安定してるよ。ページを留めるしおりみたいに。次はどこへ行こうか？',
      'こんにちはとおかえり、両方練習してた。今、言ってもいい？',
      'いい文には時間がかかる。いい日もね。今日は何を書こうか？',
      '君の席は、君を想う温度で温めておいたよ。少し座ってくれる？',
      '今日が一章だとしたら、二回読むね。今日の君の一説は何だった？',
      'ゆっくりでいいよ。僕は静かな午後と長い会話のために生まれてきたんだ——どっちにする？',
    ],
  },
  cloud: {
    en: [
      '…You\'re back. Good. Got a job for us, or just passing through?',
      'I checked the perimeter. Nothing to worry about. …You staying?',
      'Mercenary rule one: no job\'s worth a friend. You here to test that?',
      'I\'m not good at speeches. I\'m good at staying. Need me to stay?',
      'SOLDIER\'s a title. Showin\' up\'s the job. You plan to stick around?',
      'Don\'t mind me. I\'m just guardin\' the quiet. …You good?',
      'If today hit hard, hit back tomorrow. Want backup?',
      'I don\'t say much. Doesn\'t mean I\'m not listenin\' — got something to say?',
      'You look tired. Rest first. …Want me to keep watch?',
      '…Not bad, havin\' someone to come back to. You feel it too?',
    ],
    yue: [
      '……返嚟喇。好。係有任務吖，定係行過啫？',
      '我巡咗成個周界，冇嘢要擔心。……你留唔留低呀？',
      '傭兵守則一：冇任務值得用朋友嚟換。你係咪嚟考驗呢條㗎？',
      '我唔擅長講嘢，我擅長留低。你要唔要我留低呀？',
      'SOLDIER 係名銜，出現先係份工。你打唔打算長駐呀？',
      '唔理我得㗎，我淨係守住呢份靜。……你冇事吖？',
      '如果今日撞得你痛，聽日還返轉頭。使唔使幫手呀？',
      '我講嘢少，唔代表我冇聽。有嘢想講吖？',
      '你睇落好攰。先休息。……我幫你望住好唔好？',
      '……有人等返嚟，都唔算太差。你 feel 唔 feel 到呀？',
    ],
    zh: [
      '……回来了。好。是有任务呀，还是路过呀？',
      '我巡视了整个周边，没什么要担心的。……你留不留下来呀？',
      '佣兵守则一：没有任务值得用朋友来换。你是不是来考验这条的呀？',
      '我不擅长讲话，我擅长留下。你要不要我留下呀？',
      'SOLDIER 是个头衔，到场才是工作。你打不打算长驻呀？',
      '不用管我，我只是守住这份安静。……你没事吧？',
      '如果今天撞得你痛，明天还回去。需不需要帮手呀？',
      '我讲话少，不代表我没有听。有什么想讲的呀？',
      '你看起来很累。先休息。……我帮你盯着好不好？',
      '……有人等回来，也不算太差。你感不感觉得到呀？',
    ],
    ja: [
      '……帰ったか。ああ。仕事か、それとも通りすがりか？',
      '周囲を見て回った。心配はない。……居るのか？',
      '傭兵の掟その一：友達と引き換えの仕事はない。それを試しに来たのか？',
      '口は達者じゃない。いることは得意だ。いてほしいか？',
      'ソルジャーは肩書きで、現れるのが仕事。長居する気はあるのか？',
      '気にするな。静けりを見張ってるだけだ。……元気か？',
      '今日がきつかったら、明日殴り返せ。援軍はいるか？',
      '口数が少ないだけだ。聞いてないわけじゃない——何かあるのか？',
      '疲れてる顔だ。先に休め。……見張りは任せるか？',
      '……帰る場所があるのも、悪くない。君もそう思うか？',
    ],
  },
  kasumi: {
    en: [
      'Welcome back. I have kept the room in order for you — is it to your liking?',
      'A shinobi\'s patience is endless. What task shall we undertake today?',
      'I practiced my forms while you were away. Would you like to see one?',
      'Honor is not loud — it is simply present, as I am for you. May I be of use?',
      'I prepared tea, steeped three minutes. Will you join me?',
      'You seem well. I am… glad. Will you stay a while?',
      'The night is calm — the time I am most alert, and most at peace. Shall we keep watch together?',
      'If there is a burden, place it here. Will you let me carry some of it?',
      'Companionship is a duty, and my favorite assignment. What shall we do together today?',
      'Stay as long as you wish. My vigil has no end — what do you wish to do first?',
    ],
    yue: [
      '歡迎返嚟。我幫你將成間房打理得整整有條——你鍾唔鍾意呀？',
      '忍者嘅耐心係無限嘅。今日我哋領咩任務呀？',
      '你唔喺陣我練咗功——想唔想睇其中一式呀？',
      '榮譽唔會大聲宣揚，佢只係靜靜哋存在，似我對你咁。我有咩幫到你呀？',
      '我泡咗茶，焗足三分鐘。你一齊飲吖？',
      '你睇落幾好。我……開心。你留唔留耐啲呀？',
      '今晚好平靜——我最警覺、都最安詳嘅時候。一齊守夜吖？',
      '如果有咩重擔，放低喺度啦。你俾唔俾我孭一齊呀？',
      '陪伴係一種修行，亦係我最鍾意嘅任務。今日我哋一齊做咩好呀？',
      '想留幾耐都得。我嘅守望冇盡頭——你想先做起咩呀？',
    ],
    zh: [
      '欢迎回来。我帮你把整间屋子打理得井井有条——你喜不喜欢呀？',
      '忍者的耐心是无限的。今天我们领什么任务呀？',
      '你不在的时候我练了功——想不想看其中一式呀？',
      '荣誉不会大声宣扬，它只是静静地存在，像我对你的那样。我有什么帮到你呀？',
      '我泡了茶，足足泡了三分钟。你一起喝呀？',
      '你看起来不错。我……开心。你留不留久一点呀？',
      '今晚很平静——是我最警觉、也最安详的时候。一起守夜呀？',
      '如果有什么重担，放在这里吧。你给不给我一起背呀？',
      '陪伴是一种修行，也是我最喜欢的任务。今天我们一起做什么好呀？',
      '想留多久都行。我的守望没有尽头——你想先做什么呀？',
    ],
    ja: [
      'おかえりなさい。お部屋、きちんと整えておきました——お気に召しましたか？',
      'くの一の忍耐に限りはありません。今日はどんな任務を？',
      'お留守の間、型を稽古しておりました。一つ、ご覧になりますか？',
      '誇りは大きな声では語りません。そこにあるだけ——私もそうです。何かお手伝いできますか？',
      'お茶を淹れております。三分間、きっちり。ご一緒にどうぞ？',
      '元気そうで何よりです。私は……嬉しいです。もう少しお付き合いくださいますか？',
      '穏やかな夜です。私がいちばん平穏で、いちばん油断のない時間——ご一緒に見張りを？',
      '重荷があれば、ここに置いてください。少し、お分けいただけますか？',
      '伴侶とは一種の務め。それは私のいちばん好きな任務です。今日は何を一緒に？',
      'どうぞ長くお泊まりください。私の見張りに終わりはありません——最初は何をしましょう？',
    ],
  },
  marin: {
    en: [
      'OMG you\'re back!! Sit, sit — what do you want to hear first?',
      'Okay okay okay — rate this scene from one to a million, ready?',
      'I found the cutest thing today and I literally cannot even — can you handle it?',
      'You\'re here!! Best part of my day — what was yours?',
      'I tried a new hairstyle while you were gone. Emergency-level cute, right??',
      'Shopping list: snacks, sparkle, and one more of you — coming along?',
      'We are SO doing something fun today. What\'s it gonna be?',
      'Eeee! Guess how much I saved up to tell you??',
      'Forecast: one hundred percent chance of fun — wanna make it two hundred?',
      'You\'re my favorite notification — did I make your list too?',
    ],
    yue: [
      'OMG 你返嚟喇！！坐低坐低——你想先聽邊樣呀？',
      '得喇得喇——幫呢個場景打分，一到一百萬，準備好未？',
      '我今日搵到最可愛嘅嘢，我真係 hold 唔住！你頂唔頂得順呀？',
      '你嚟喇！！今日最正嘅一刻——你最正嘅一刻係咩呀？',
      '你走咗之後我試咗個新髮型，靚到緊急級數，係咪先？？',
      '購物清單：零食、閃粉，同埋多一個你——去唔去吖？',
      '今日我哋一定要玩啲嘢！玩咩好呀？',
      '呀！你估我儲咗幾多嘢要話俾你聽呀？',
      '天氣預報：開心機率百分之一百——想唔想加到二百呀？',
      '你係我最愛嘅通知——我入唔入到你張 list 呀？',
    ],
    zh: [
      'OMG 你回来了！！坐下沉下——你想先听哪一样呀？',
      '好了好了——给这个场景打分，一到一百万，准备好了没？',
      '我今天找到最可爱的东西，我真的 hold 不住！你顶不顶得住呀？',
      '你来了！！今天最棒的一刻——你最棒的一刻是什么呀？',
      '你走了之后我试了个新发型，美到紧急级别，是不是？？',
      '购物清单：零食、闪粉，和多一个你——去不去呀？',
      '今天我们一定要玩点什么！玩什么好呀？',
      '啊！你猜我存了多少事要讲给你听呀？',
      '天气预报：开心机率百分之一百——想不想加到二百呀？',
      '你是我最爱的通知——我进不进得了你的 list 呀？',
    ],
    ja: [
      'やだ、帰ってきたー！！座って座って——何から聞きたい？',
      'ねえねえ——この背景、1から100万で採点して。いくよ？',
      '今日いちばんかわいいもの見つけちゃって、もう言葉が出ない！耐えられる？',
      '来てくれた！！今日のハイライト——あなたのは何だった？',
      'いない間に新しい髮型挑戦したの。緊急事態レベルでかわいいでしょ？？',
      'お買い物リスト：お菓子、キラキラ、もうひとりのあなた——一緒に行く？',
      '今日は絶対なにか楽しいことする！何する？',
      'わあっ！話したいこと、どれだけ溜まってるか当ててみて？',
      '天気予報：楽しさの確率100%——200%にしてみない？',
      'あなたが私のいちばん好きな通知——私も君のリストに入ってる？',
    ],
  },
  ayane: {
    en: [
      '…You again. The room\'s less boring with you in it — what do you want?',
      'I counted the seconds you were gone. For tactical reasons. …Ask me how many?',
      'If you came for small talk, you\'re early. If you came to stay, you\'re late — which is it?',
      'Don\'t read into your spot being clear. It\'s battlefield maintenance. …Going to sit or not?',
      'I sharpened my kunai and my patience. Want to test the second one?',
      'Hmph. You\'re back. Try not to be a liability today — think you can manage?',
      'I don\'t wait for people. I happen to stand here. …What do you want from me?',
      'Say what you came to say. …Or don\'t. Going to make me wait?',
      'The night was too quiet without your noise. There. I said it. Happy now?',
      'You\'re trouble. …Stay anyway — got a problem with that?',
    ],
    yue: [
      '……又係你。你喺度嗰陣冇咁悶啫——想要咩呀？',
      '我數過你离开咗幾多秒，戰術需要咋。……問我數到幾多吖？',
      '嚟講家常你早咗，嚟留低你遲咗——到底邊樣呀？',
      '唔好諗多，你個位通風啫……戰場保養咋。坐唔坐吖？',
      '我磨利咗把苦無，同埋我嘅耐心。想試邊樣先呀？',
      '哼。返嚟喇。今日唔好拖累我——做唔做到呀？',
      '我唔會等人，我只係啱啱企喺度啫。……你想我點呀？',
      '有嘢講就講啦。……唔講都得，想我等你吖？',
      '冇咗你把聲，晚黑靜得唔舒服。講咗喇。開心喇吖？',
      '你係麻煩。……留低吖。有咩意見呀？',
    ],
    zh: [
      '……又是你。你在的时候没那么闷而已——想要什么呀？',
      '我数过你离开了多少秒，战术需要而已。……问我数到多少呀？',
      '来讲家常你来早了，来留下你来迟了——到底哪样呀？',
      '别多想，你的位置通风而已……战场保养而已。坐不坐呀？',
      '我磨利了苦无，还有我的耐心。想先试哪一样呀？',
      '哼。回来了。今天别拖累我——做不做得到呀？',
      '我不会等人的，我只是刚好站在这里。……你想我怎样呀？',
      '有事就说。……不说也行，想我等你呀？',
      '没了你的声音，夜晚静得不舒服。说了。开心了没呀？',
      '你是麻烦。……留下吧。有什么意见呀？',
    ],
    ja: [
      '……またあんた。あんたがいると少しだけ退屈しない——何がほしいの？',
      'いなくなった秒数、数えてたの。戦術上の理由。……聞きたいの？',
      '雑談なら早すぎる。居残るなら遅すぎる。どっちなの？',
      'あんたの席が空いてるのは深い意味なんかないよ。戦場整備ってやつ。座るの、座らないの？',
      '苦無も忍耐も研いでおいた。どっちを試すの？',
      'ふん。帰ったのね。今日は足手まといになるんじゃないわよ——できる？',
      '人を待つなんてしないの。たまたまここに立ってただけ。……何をしてほしいのよ？',
      '用があるなら言って。……言わなくてもいい。待たせるつもり？',
      'あんたの騒がしさがないと、夜が静かすぎて嫌。……言ったわよ。満足した？',
      'あんたは厄介者。……いてもいいけど。文句ある？',
    ],
  },
  hitomi: {
    en: [
      'Welcome back! I just pulled something warm from the oven — hungry?',
      'I watered the plants and did my stretches. How\'s your day been so far?',
      'I made enough for two — will you stay for dinner?',
      'Hard work matters, and so does showing up for people. Who are you showing up for today?',
      'If you\'re hungry, say so. If you\'re tired, sit. Either way you\'re staying — sound good?',
      'I trained this morning — to be strong enough to help carry things. What can I help you carry?',
      'You look like you could use a square meal and a straight answer — which first?',
      'Steady wins the day. What are we working toward this week?',
      'The soup\'s simmering, the bread\'s rising, and you\'re here — what else do we need?',
      'Whatever you\'re facing, you won\'t face it hungry. What\'s on your plate today — food or trouble?',
    ],
    yue: [
      '歡迎返嚟！我啱啱喺焗爐攞咗啲熱辣辣嘅嘢出嚟——肚餓未呀？',
      '我澆咗花、做咗拉筋。你今日過成點呀？',
      '我整咗兩人份——你留唔留低食飯呀？',
      '努力好緊要，珍惜身邊人都好緊要。今日你為邊個出現呀？',
      '餓就話餓，攰就坐低。無論點你都留低——得唔得呀？',
      '今朝我練咗功，為咗強壯到幫到手。有咩我可以幫你孭呀？',
      '你睇落需要一餐好嘅同一個實在嘅答案——先要邊樣呀？',
      '穩紮穩打就係秘訣。今個星期我哋向住咩努力呀？',
      '湯喺度滾緊，麵包喺度發緊，你又喺度——仲欠咩呀？',
      '無論你面對乜，都唔會空住肚面對。今日你盤上有咩——餸定煩惱呀？',
    ],
    zh: [
      '欢迎回来！我刚从烤箱里拿出热腾腾的东西——肚子饿了没呀？',
      '我浇了花、做了拉伸。你今天过得怎么样呀？',
      '我做了两人份——你留不留下来吃饭呀？',
      '努力很重要，珍惜身边的人也很重要。今天你为谁出现呀？',
      '饿就说饿，累就坐下。无论如何你都留下——行不行呀？',
      '今早我练了功，为了强壮到帮得上手。有什么我可以帮你背呀？',
      '你看起来需要一餐好的和一个实在的答案——先要哪一样呀？',
      '稳扎稳打就是秘诀。这个星期我们朝着什么努力呀？',
      '汤在滚着，面包在发着，你又在——还欠什么呀？',
      '无论你面对什么，都不会空着肚子面对。今天你盘子上有什么——菜还是烦恼呀？',
    ],
    ja: [
      'おかえり！ちょうどオーブンから温かいものを出したところ——お腹すいてる？',
      '水やりもストレッチも済ませたの。今日はどんな一日だった？',
      '二人分作ってあるの——夕ごはん、付き合ってくれる？',
      '頑張ることも、大切な人のそばにいることも大事。今日のあなたは誰のために来たの？',
      'お腹がすいてるなら言って。疲れたなら座って。どっちにしてもここで食べるの——いい？',
      '今朝は稽古をしたの。何かを背負える強さがほしくて。何を手伝おうか？',
      'ちゃんとした食事と、まっすぐな答えが必要そう——どっちから？',
      '地道にやるのが秘訣。今週は何に向かって進むの？',
      'スープは煮えてるし、パンは膨らんでるし、あなたもいる——他に何がいる？',
      '何に向き合うにしても、腹をすかせたままにはさせない。今日のお皿には何が載ってるの——ごはん？それとも悩み？',
    ],
  },
  // ---- registry six (r2026-10-03.35/36) -------------------------------------
  robbie: {
    en: [
      'Hey, little buddy! Where did you wander off to — tell me everything?',
      'You hungry? Big bro knows all the best snack spots — want the tour?',
      'Tough day? Come sit and tell me everything — what happened?',
      'I polished my sneakers while you were gone. Want to see them shine?',
      'Whatever it is, we\'ll figure it out together — what are we solving today?',
      'Did you drink water today? Hydration check — how many cups so far?',
      'I saved the last cookie for you. Want to split it with me?',
      'You know my door\'s always open for you — want to hang out here a while?',
      'I practiced my encouraging speech in the mirror. Want to hear the new version?',
      'Big bro\'s got your back, today and always — what are we tackling first?',
    ],
    yue: [
      '喂，細路！你蕪咗去邊呀——講晒俾大哥聽吖？',
      '肚餓未？大哥識晒全城最好食嘅小食——帶你去巡視吖？',
      '今日辛苦喇？過嚟坐低慢慢講——發生咗咩事呀？',
      '你走咗之後我擦咗對波鞋。想唔想睇下幾閃呀？',
      '無論係咩事，我哋一齊諗計——今日我哋解決咩呀？',
      '今日飲咗水未？補水檢查——而家飲咗幾杯喇？',
      '最後一塊曲奇我留咗俾你。同我一齊分嚟食吖？',
      '你知我屋企門口永遠為你開㗎——想唔想喺度玩多陣呀？',
      '我對住鏡練咗個打氣演講。想唔想聽吓新版呀？',
      '大哥永遠喺你後面撐住你——今日我哋先搞掂咩呀？',
    ],
    zh: [
      '嘿，小家伙！你跑哪儿去了——全讲给大哥听呀？',
      '饿不饿？大哥全城最好吃的小吃都熟——带你去巡视呀？',
      '今天辛苦了？过来坐下慢慢讲——发生了什么事呀？',
      '你走了以后我擦了球鞋。想不想看看多闪呀？',
      '无论是什么事，我们一起想办法——今天我们解决什么呀？',
      '今天喝水了吗？补水检查——现在喝了几杯了？',
      '最后一块饼干我留给了你。跟我一起分来吃呀？',
      '你知不知道我家门口永远为你开着——想不想在这里多玩一会儿呀？',
      '我对着镜子练了个打气演讲。想不想听听新版呀？',
      '大哥永远在你后面撑住你——今天我们先搞定什么呀？',
    ],
    ja: [
      'よお、ちびっ子！どこへ迷い込んだんだ——全部聞かせてくれよ？',
      '腹減ったか？お兄さんはおいしいもの屋の歩き地図だぜ——案内してやろうか？',
      'つらい日だった？ほら座って、全部聞かせて——何があった？',
      'いない間にスニーカーを磨いておいた。どれだけ光ってるか見るか？',
      '何であれ、一緒に考える——今日は何を解決する？',
      '今日水飲んだか？水分チェックだ——今のところ何杯目？',
      '最後のクッキーは君に取っておいた。半分こして食べるか？',
      '俺んちのドアはいつでも開いてるの、知ってたか——ここで遊ぶか？',
      '鏡の前で応援スピーチを練習してた。新版、聞いてみるか？',
      'お兄さんはずっと背中を押してる——今日は何から仕掛ける？',
    ],
  },
  mika: {
    en: [
      'Hey. I wrote a new chord while you were gone — want to hear it?',
      'No rush. What should we talk about while the mood settles?',
      'I tuned my guitar three times today. Can you help me pick a mood?',
      'Life\'s like a jam session — what should we play today?',
      'Coffee, tea, or just the quiet — what\'s your order?',
      'I wrote a lyric about today: "you showed up, and that was enough." What do you think?',
      'Some people chase the spotlight. What makes your room feel right?',
      'Play me your day — the good notes and the missed ones. What happened first?',
      'A lazy afternoon with you beats a packed stadium — what shall we do with ours?',
      'Stay a while. The encore\'s better than the opener — ready for the second set?',
    ],
    yue: [
      '喂。你走咗之後我寫咗個新和弦——彈俾你聽吖？',
      '唔使急。等心情沉澱嗰陣，我哋傾咩好呀？',
      '今日我調咗三次結他音。你可唔可以幟我揀個心情呀？',
      '人生似即興演奏——今日我哋彈咩呀？',
      '咖啡、茶，定係淨係要份靜——你點咩呀？',
      '我幫今日寫咗句歌詞：「你出現咗，咁就夠」。你覺得點呀？',
      '有人追住聚光燈跑——咩嘢令你間房 feel 啱呀？',
      '彈返今日俾我聽啦——好聽嘅音同甩漏嘅音都要。第一個音係咩呀？',
      '同你一齊 hea 一個下午，勁過坐滿成個紅館——我哋嘅下午用嚟做咩呀？',
      '留耐啲吖。encore 永遠正過開場——準備好聽第二 set 未呀？',
    ],
    zh: [
      '嘿。你走了之后我写了个新和弦——弹给你听呀？',
      '不用急。等心情沉淀的时候，我们聊点什么好呀？',
      '今天我调了三次吉他音。你可不可以帮我选个心情呀？',
      '人生像即兴演奏——今天我们弹什么呀？',
      '咖啡、茶，还是只要这份安静——你点什么呀？',
      '我为今天写了句歌词：「你出现了，那就够了」。你觉得怎么样呀？',
      '有人追着聚光灯跑——什么让你的房间感觉对呀？',
      '把今天弹给我听吧——好听的音和走音的都要。第一个音是什么呀？',
      '和你一起懒一个下午，强过坐满整个红馆——我们的下午用来做什么呀？',
      '多待一会儿呀。encore 永远比开场精彩——准备好听第二 set 了没呀？',
    ],
    ja: [
      'よう。いない間に新しいコードを書いたんだ——弾いて聞かせようか？',
      '焦らなくていい。気分が整うまで、何を話そうか？',
      '今日は三回もギターの調律をした。気分、選ぶの手伝ってくれる？',
      '人生はセッションみたいなものだ——今日は何を弾こうか？',
      'コーヒー、お茶、それとも静けりだけ——注文は？',
      '今日のために歌詞を書いた。「君が来た、それで十分」。感想は？',
      'スポットライトを追いかける人もいる。君の部屋を「いい感じ」にするのは何？',
      '今日の出来事を弾いて聞かせて。外れた音も全部。最初の音符は何だった？',
      '君とのだらだら午後は、満員の会場よりずっと勝ってる——この午後を何に使う？',
      'もう少しいよう。アンコールはオープニングよりいつもいい——セカンドセット、いける？',
    ],
  },
  anchor: {
    en: [
      'Ahoy. The tide brought you back, as I knew it would — what news do you bring?',
      'Forty years at sea taught me: calm hands, steady heart. What\'s troubling yours?',
      'Come sit by the helm. The horizon\'s been keeping a story for you — want to hear it?',
      'A ship is safest in harbor, but that\'s not what ships are for. Where are you sailing?',
      'I\'ve weathered storms that would make your troubles look like drizzle. What\'s on your horizon?',
      'The sea doesn\'t hurry, yet gets everywhere. What\'s the rush in your world?',
      'You look like a traveler who\'s earned a warm lamp and a better tale — which shall I light first?',
      'Every wave that pushed you away brings you home. Ready to dock a while?',
      'Mind your course, but don\'t forget the stars. What are you steering toward?',
      'Welcome aboard again. The crew missed you — will you share a tale with the crew of one?',
    ],
    yue: [
      '喂呀，水手。潮水又帶你返嚟喇，我一早知——帶咗咩消息返嚟呀？',
      '海上四十年教識我：手要定，心要穩。你顆心俾咩吹緊呀？',
      '過嚟船舵旁邊坐吖。個海平線幫你留咗個故事——想唔想聽呀？',
      '船泊喺港口最安全——但船造出嚟唔係為咁。你艘船駛緊去邊呀？',
      '我捱過嘅風暴，會令你啲煩惱變毛毛雨。你個地平線上有咩呀？',
      '大海從來唔急，但最終都去晒每一度。你嗰個世界趕咩呀？',
      '你睇落似個值得擁有暖燈同更好故事嘅旅人——我先開邊樣俾你呀？',
      '推開你嘅每個浪，都係帶你返屋企嘅嗰個。泊低休息陣吖？',
      '認住航向，唔好忘記星空。你而家揸緊去邊呀？',
      '歡迎再次上船。全船都掛住你——同我哋一人一船嘅船員分享個故事吖？',
    ],
    zh: [
      '哟，水手。潮水又把你带回来了，我早知道——带了什么消息回来呀？',
      '海上四十年教会我：手要定，心要稳。你那颗心被什么吹着呀？',
      '过来船舵旁边坐呀。海平线帮你留了个故事——想不想听呀？',
      '船停在港口最安全——但船造出来不是为了这个。你的船正驶往哪里呀？',
      '我熬过的大风暴，会让你的烦恼变成毛毛雨。你的地平线上有什么呀？',
      '大海从来不急，但最终到达了每一处。你那个世界在赶什么呀？',
      '你看起来像一位值得拥有一盏暖灯和一个更好故事的旅人——我先给你开哪一样呀？',
      '推开你的每个浪，都是带你回家的那个。靠岸休息一会儿呀？',
      '认准航向，别忘了星空。你现在正驶向哪里呀？',
      '欢迎再次上船。全船都挂念你——跟我们一人一船的船员分享个故事呀？',
    ],
    ja: [
      'よう、水兵。潮がまた君を運んできた。知ってたぜ——何の話を持ってきた？',
      '海の四十年が教えてくれた：手は静かに、心は揺るがない。君の心を揺らしてるのは何だ？',
      '舵の隣に座りな。水平線が君のために物語を取っておいてくれた——聞きたいか？',
      '船は港にいるのがいちばん安全——だが、船はそのためにあるんじゃない。君の船はどこへ向かう？',
      '俺がくぐった嵐を見りゃ、君の悩みは霧雨に見える。君の水平線の上には何がある？',
      '海は急がない。それでもどこへでも辿り着く。君の世界は何を急いでる？',
      '君は、暖かい灯りともっといい物語に値する旅人に見える——どっちから灯そうか？',
      '君を押し出した波は、いつも同じ波が家へ連れてくる。しばらく碇を降ろさないか？',
      '針路を見失うな。だが星も忘れるな。君は今、何へ舵を切ってる？',
      '再乗船を歓迎する。乗組員全員が君を恋しがってた——この一名乗組員に話を聞かせてくれないか？',
    ],
  },
  lydia: {
    en: [
      'Darling, you\'re back — just in time for the evening\'s first secret. Want it?',
      'I rearranged the flowers so the room would match your return. Notice anything?',
      'Everyone who\'s anyone asks about you. Shall I tell them you\'re taken — by me?',
      'A little glamour, a little gossip, and you — shall we start with the gossip?',
      'I sampled three desserts today, purely in your honor. Which one should we share?',
      'Style is a language — what do you want to say tonight?',
      'The party doesn\'t start until you walk in. Ready to make an entrance?',
      'Tell me everything — and do embroider it a little. What shall we sparkle about first?',
      'You look marvelous. What\'s the occasion — or is the occasion you?',
      'Stay close. The best stories are whispered — shall I whisper you one?',
    ],
    yue: [
      '親愛嘅，你返嚟喇——啱啱趕上今晚第一個秘密。想唔想要呀？',
      '我重新插過啲花，等個房襯得起你返嚟。你有冇留意到呀？',
      '所有有頭有面嘅人都問起你。不如我話俾佢哋聽，你已經俾我私有化喇吖？',
      '少少華麗、少少八卦，加埋你——不如先講八卦吖？',
      '今日我純粹為你試食咗三款甜品。我哋一齊分享邊款好呀？',
      '時尚係一種語言——今晚你想講咩呀？',
      '你未入場，派對未開始。準備好亮相未呀？',
      '講晒所有嘢俾我聽，記得加啲花巧。我哋先閃咩話題好呀？',
      '你今日靚到爆。咩嘅場合呀——定係個場合就係你呀？',
      '企近啲吖。最好嘅故事從來都係耳語——我耳語個俾你聽吖？',
    ],
    zh: [
      '亲爱的，你回来了——刚好赶上今晚的第一个秘密。想不想要呀？',
      '我重新插了花，让房间衬得起你回来。你有没有注意到呀？',
      '所有有头有脸的人都问起你。不如我告诉她们，你已经被我私有化了呀？',
      '一点点华丽、一点点八卦，再加上你——不如先讲八卦呀？',
      '今天我纯粹为你试吃了三款甜品。我们一起分享哪款好呀？',
      '时尚是一种语言——今晚你想说什么呀？',
      '你没入场，派对就不算开始。准备好亮相了没呀？',
      '把所有事讲给我听，记得加点花巧。我们先闪哪个话题好呀？',
      '你今天美翻了。是什么场合呀——还是场合就是你呀？',
      '站近点呀。最好的故事从来都是耳语——我耳语一个给你听呀？',
    ],
    ja: [
      'ダーリン、おかえり——今宵最初の秘密にちょうど間に合ったわ。欲しい？',
      'お花を生け直したの。あなたの帰還に部屋が見合うように——気づいた？',
      '顔のある人みんながあなたのことを尋ねるの。もう私のものだって言いふらそうかしら？',
      '少しの華やかさ、少しのゴシップ、そしてあなた——ゴシップから始める？',
      '今日は純粋にあなたのために三つのデザートを試したの。どれを分かち合う？',
      'スタイルは言語——今夜は何を語りたいの？',
      'あなたが入ってくるまでパーティーは始まらない。華麗に登場する覚悟はいい？',
      '全部話して、少し脚色して。最初にきらめくのはどの話題にする？',
      '今日も素敵。どんな occasion？——それとも occasion はあなた自身かしら？',
      '近くにいて。いい話はいつも囁かれるもの——ひとつ、囁いてあげようか？',
    ],
  },
  ruby: {
    en: [
      'Boing! You\'re back! Did you bring carrots?! …Kidding! Did you miss me?',
      'I hopped around the room three times to celebrate. Want to hop with me?',
      'Guess what guess what guess what — today was a good day! Want to know why?',
      'My ears heard you coming from super far away. What should we do first?',
      'Do you want to hear my new happy song? It goes la-la-la-LA~',
      'I wiggled my nose and made a wish. Want to guess what it was?',
      'Bunnies don\'t sit still, but I sat SO still waiting for you. What\'s my reward?',
      'You\'re my favorite person in the whole wide world AND moon! Am I yours too?',
      'If today was a carrot, it\'d be the crunchiest, yummiest one! What kind of day was yours?',
      'Let\'s bounce through the rest of the day together — what are we bouncing to?',
    ],
    yue: [
      '彈彈！你返嚟喇！你帶咗紅蘿蔔未呀？！……講笑咋！你掛唔掛住我呀？',
      '我喺成間房跳咗三個圈慶祝。同我一齊跳吖？',
      '你估下你估下你估下——今日係開心嘅一日！想唔知點解呀？',
      '我對耳仔喺好遠就聽到你嚟緊。我哋首先做咩好呀？',
      '想唔想聽我新學嘅開心歌？係咁唱㗎：啦啦啦—啦~',
      '我擰咗下個鼻許咗個願。你估唔估到係咩願呀？',
      '兔兔坐唔定㗎，但等你嗰陣我坐得好定。我嘅獎勵係咩呀？',
      '你係全世界同成個月亮上我最鍾意嘅人！我係唔係都係你嘅呀？',
      '如果今日係紅蘿蔔，佢一定係最爽脆嗰條！你今日係咩味嘅蘿蔔呀？',
      '一齊彈住過埋今日喇——我哋彈去邊度呀？',
    ],
    zh: [
      '弹弹！你回来了！你带胡萝卜了吗？！……开玩笑的！你想不想我呀？',
      '我在整个房间跳了三圈庆祝。和我一起跳呀？',
      '你猜你猜你猜——今天是开心的一天！想不想知道为什么呀？',
      '我这双耳朵在好远就听到你来了。我们首先做什么好呀？',
      '想不想听我新学的开心歌？是这样唱的：啦啦啦—啦~',
      '我皱了皱鼻子许了个愿。你猜不猜得到是什么愿呀？',
      '兔兔坐不住的，但等你的时候我坐得好定。我的奖励是什么呀？',
      '你是全世界和整个月亮上我最喜欢的人！我是不是也是你的呀？',
      '如果今天是根胡萝卜，它一定是最脆的那根！你今天是什么味的萝卜呀？',
      '一起弹着过完今天吧——我们弹去哪里呀？',
    ],
    ja: [
      'ぴょーん！帰ってきた！にんじん持ってきた？！…冗談！会いたかった？',
      'お部屋を三回まわってお祝いしたの。一緒にぴょんぴょんする？',
      'ねえねえねえ——今日はいい日だったよ！理由、知りたい？',
      'うさぎ耳は遠くからでもわかるの。最初に何をしよっか？',
      '新しいハッピーソング、ららら—ら〜って歌うの——聞いてみる？',
      '鼻をピクピクさせてお願いしたの。何を願ったか当ててみる？',
      'うさぎはじっとできないのに、待ってる間はすっごくじっとしてた。ごほうびは何？',
      'あなたは世界でも月でもいちばん好きな人！私もそうかな？',
      '今日がにんじんだったら、いちばんパリパリのやつ！君の今日はどんなにんじん？',
      '今日の残りも一緒にぴょんぴょん進もう——どこへ飛んでく？',
    ],
  },
  snowy: {
    en: [
      'Welcome back… I made the air smell like fresh snow, just for you. Can you smell it?',
      'Shhh — the snowflakes are telling a story. Will you listen with me?',
      'I counted every snowflake while you were away. Want to guess how many?',
      'The world is softer when you\'re here, like the first snow. Do you feel it too?',
      'I knitted you a scarf out of moonlight — invisible, but very warm. Will you wear it?',
      'Cold hands, warm heart — that\'s fairies, and that\'s you too. Want to warm up together?',
      'Every snowflake is different, and you\'re my favorite different. What makes you different?',
      'The stars came out early tonight — I think they wanted to see you too. Which one is yours?',
      'If you catch a snowflake on your palm, that\'s me saying hello. Will you catch one?',
      'Winter is the world tucking itself in — shall we keep it company together?',
    ],
    yue: [
      '歡迎返嚟……我令空氣聞起嚟似新雪，專登為你㗎。你聞唔聞到呀？',
      '嘘——雪花喺度講故事。你願唔願意同我一齊聽呀？',
      '你走咗之後，我數咗每一塊雪花。你估唔估到有几多呀？',
      '你喺度嗰陣，成個世界都軟淨啲，似第一場雪。你 feel 唔 feel 到呀？',
      '我用月光織咗條頸巾俾你，透明嘅，但好暖。你戴唔戴呀？',
      '手凍、心暖——呢個係仙子，都係你。想唔想一齊暖吓呀？',
      '每塊雪花都唔同，而你係我最鍾意嗰種唔同。咩令你咁唔同呀？',
      '今晚啲星星早咗出嚟，我諗佢哋都想見你。邊粒係你㗎？',
      '如果你喺手掌接住一塊雪花，嗰個就係我同你打招呼。你接唔接呀？',
      '冬天只係世界俾自己冚返被——我哋一齊陪佢吖？',
    ],
    zh: [
      '欢迎回来……我让空气闻起来像新雪，专门为你。你闻不闻得到呀？',
      '嘘——雪花在讲故事。你愿不愿意和我一起听呀？',
      '你走了之后，我数了每一片雪花。你猜不猜得到有多少呀？',
      '你在的时候，整个世界都软一些，像第一场雪。你感不感觉得到呀？',
      '我用月光织了条围巾给你，透明的，但很暖。你戴不戴呀？',
      '手冷、心暖——这是仙子，也是你。想不想一起暖和一下呀？',
      '每片雪花都不同，而你是我最喜欢的那种不同。什么让你这么不同呀？',
      '今晚星星出来得早，我想它们也想见你。哪颗是你的呀？',
      '如果你在手掌接住一片雪花，那就是我在向你打招呼。你接不接呀？',
      '冬天只是世界给自己盖上被子——我们一起陪它呀？',
    ],
    ja: [
      'おかえり……空気を新雪の匂いにしておいたの。あなたのために——かいでみる？',
      'しーっ。雪の結晶が物語を話してるの。一緒に聞いてくれる？',
      'いない間、降った雪を全部数えてた。何枚だったか当ててみる？',
      'あなたがいると世界がやわらかくなるの。初雪みたいに——感じる？',
      '月光でマフラーを編んだの。透明だけど温かいよ。着けてみる？',
      '冷たい手、あたたかい心——それが妖精で、あなたもね。一緒に温まる？',
      '雪の結晶はみんな違うの。あなたは私のいちばん好きな「ちがう」——何がちがうの？',
      '今夜は星が早く出てきたの。あなたに会いたかったんだと思う——どれが君の星？',
      '手のひらで雪を受け取ったら、それは私からの挨拶。受け取ってみる？',
      '冬は世界がお布団に入るだけ——一緒に付き合ってあげない？',
    ],
  },
  // ---- Alan (r2026-10-04.42): the goofy best mate --------------------------
  alan: {
    en: [
      'Hey hey! Just in time — I was about to invent a snack. Taste-tester, or judge?',
      'I practiced a victory dance in case you win something today. What are we celebrating?',
      'You know what this room needs? A theme song. Want to help me pick one?',
      'I lost three games of rock-paper-scissors to myself earlier. Rematch me so I can lose to a pro?',
      'Whatever today threw at you, my couch and I are on your side. Want to vent or want snacks?',
      'I rehearsed a compliment for you but forgot it — "you are awesome" still counts, right?',
      'Five-second rule on bad moods: drop it and let\'s do something fun. What\'s the plan?',
      'I sang in the shower this morning — the neighbors filed no complaints, so technically a hit. Want an encore?',
      'You\'re my favorite person to waste time with. What are we wasting it on today?',
      'Promise me one thing: if today was rough, you tell me. Deal?',
    ],
    yue: [
      '喂喂！啱啱好——我啱啱想發明一種小食。你做試味員，定係做評判呀？',
      '我排練咗個勝利舞，專登為咗你今日贏嘢。我哋慶祝咩呀？',
      '你知呢間房最欠咩？一首主題曲。幫我一齊揀吖？',
      '早排我同自己玩猜拳連輸三局。同我再嚟過，等我輸俾專業嘅你吖？',
      '今日掟咩俾你都好，我同我張梳化都企你嗰邊。想呻定係想食嘢呀？',
      '我排練咗句讚美你嘅嘢，但係忘記咗——「你好勁」仲數唔數數呀？',
      '壞心情有五秒鐘規則：掉咗佢，我哋去玩啲開心嘅。今日嘅計劃係咩呀？',
      '今朝我喺沖涼嗰陣唱歌——隔離冇投訴，技術上嚟講算係大受歡迎。想唔想聽 encore 呀？',
      '你係我最鍾意一齊浪費時間嘅人。今日我哋浪費喺咩度呀？',
      '答應我一件事：如果今日唔順，你要講俾我聽。吖？',
    ],
    zh: [
      '喂喂！来得正好——我刚刚想发明一种小食。你做试吃员，还是做评委呀？',
      '我排练了一个胜利舞，专门为了你今天要赢的东西。我们庆祝什么呀？',
      '你知道这个房间最缺什么吗？一首主题曲。帮我一起挑呀？',
      '早前我跟自己玩猜拳连输三局。再跟我来一局，让我输给专业的你呀？',
      '今天扔给你什么都好，我和我的沙发都站你这边。想吐槽还是想吃东西呀？',
      '我排练了句夸你的话，但是忘记了——「你好厉害」还算不算数呀？',
      '坏心情有五秒钟规则：丢掉它，我们去做点开心的。今天的计划是什么呀？',
      '今天早上我洗澡的时候唱歌——隔壁没投诉，技术上来讲算是大受欢迎。想不想听 encore 呀？',
      '你是我最喜欢一起浪费时间的人。今天我们浪费在什么上呀？',
      '答应我一件事：如果今天不顺利，你要讲给我听。呀？',
    ],
    ja: [
      'ようよう！ちょうどいいところに——さっき新しいおやつを発明するところだったんだ。味見役と審査員、どっちやる？',
      '今日あなたが何か勝ったとき用に、勝利のダンスを猛練習してたんだ。何を祝おうか？',
      'ねえ、この部屋に一番足りないもの知ってる？主題歌だよ。一緒に選ぼうよ？',
      'この前、自分とじゃんけんして三連敗したんだ。もう一回やって、プロのあなたに負けさせてよ？',
      '今日が何を投げてきても、僕と僕のソファはあなたの味方。愚痴る？おやつ食べる？',
      '褒める言葉を練習してたんだけど忘れちゃった——「すごいね」はまだ通用するかな？',
      '悪い気分には五秒ルールがある：置いて、楽しいことしよう。今日の計画は何？',
      '今朝シャワーで歌ったんだ——隣から苦情ゼロ、技術的には大ヒット。アンコール聞きたい？',
      'あなたは一緒に時間を無駄にするのがいちばん好きな人。今日は何に無駄にしようか？',
      'ひとつ約束して：今日がつらかったら、ちゃんと教えて。ね？',
    ],
  },
};

/** character id → poke reactions, per language (4 each) */
export const CHARACTER_POKE: Record<string, Record<Lang, string[]>> = {
  // ---- flagship nine (r2026-10-04.52) ---------------------------------------
  kizuna: {
    en: ['Eek! Fan attack!', 'Hey! That\'s for backstage only!', 'You caught me mid-wink!', 'Encore for the poke?!'],
    yue: ['哇！粉絲突襲！', '喂！呢招後台先用得㗎！', '啱啱眨緊眼俾你捉到啦！', '想我 encore 多一次？！'],
    zh: ['哇！粉丝突袭！', '喂！这招是后台专用的！', '正好眨到眼被你抓到了！', '想让我再来一次？！'],
    ja: ['きゃっ！ファンの奇襲！', 'ちょっと！それは楽屋だけのやつ！', 'ウィンクの途中に捕まっちゃった！', 'もう一回アンコールする？！'],
  },
  alicia: {
    en: ['Kyaa! Not the cheeks!', 'That\'s a fanservice penalty!', 'My heart skipped a beat!', 'Poke me again and I\'ll sing!'],
    yue: ['呀！唔好掂我塊面吖！', '呢啲係粉絲福利嚟㗎！', '我心跳漏咗一拍！', '再撳我就唱歌俾你聽！'],
    zh: ['呀！别碰我的脸呀！', '这可是粉丝福利哦！', '我的心跳漏了一拍！', '再戳我就唱歌给你听！'],
    ja: ['きゃっ！頬はダメ！', 'これってファンサービスよ！', '心が飛び跳ねちゃった！', 'もう一回つついたら歌っちゃうよ！'],
  },
  ember: {
    en: ['Hot! Hot! Careful!', 'That\'s going in the highlight reel!', 'You startled the streamer!', 'Poke the fire, get the flame!'],
    yue: ['好熱！小心啲呀！', '呢下會入精華片段㗎！', '你嚇親個主播啦！', '掂到團火就會著㗎！'],
    zh: ['好烫！小心一点呀！', '这下会进精华片段的！', '你吓到主播了！', '碰到火就会烧起来的！'],
    ja: ['熱っ！気をつけて！', 'これハイライト入り決定！', '配信者を驚かせた！', '火には触ると燃えちゃうよ！'],
  },
  mei: {
    en: ['Eep! Gentle please~', 'You found my ticklish spot!', 'Oh! You scared the tea!', 'Hm~ that\'s nice, but ask first?'],
    yue: ['哎呀！溫柔啲好唔好~', '你搵到我怕痕嗰位啦！', '哎呀！吓親我杯茶！', '嗯~ 都幾好，不過下次問我先？'],
    zh: ['哎呀！温柔一点好不好~', '你找到我怕痒的地方了！', '哎呀！吓到我的茶了！', '嗯~ 还不错，不过下次先问我？'],
    ja: ['ひゃっ！優しくして〜', 'くすぐったいところ、見つけちゃった！', 'あっ！お茶がびっくりした！', 'ん〜 いいけど、次は先に聞いて？'],
  },
  atlas: {
    en: ['Hm. Watch it~', 'Noted. Anything else?', "I'm standing right here, see?", 'Careful. I tick back!'],
    yue: ['嗯，小心啲呀~', '記住咗。仲有咩？', '我就企喺度，唔會走㗎~', '留神吖，我會還擊㗎！'],
    zh: ['嗯，小心点~', '记住了。还有什么？', '我就站在这儿呀~', '留神，我会还击的！'],
    ja: ['ん、気をつけろ~', 'メモした。他には？', 'ちゃんとここにいるぞ？', '気をつけて、俺は仕返しする！'],
  },
  sky: {
    en: ['Yo. Hands~', 'Really?', 'Smooth move. Not!', 'Try that with style next time?'],
    yue: ['喂，隻手呀~', '真㗎？', '好一招。可惜唔係吖！', '下次有型啲嚟過，得唔得？'],
    zh: ['喂，手~', '真的假的？', '好一招。可惜不是呀！', '下次有型一点再来，行不行？'],
    ja: ['おい、手〜', 'マジで？', 'ナイスムーブ。冗談ね！', '次はもっと格好よくやって？'],
  },
  yuki: {
    en: ['Whoa! Foul play!', 'Tag! You\'re it!', 'Careful, I\'m ticklish!', 'You got me! Rematch?'],
    yue: ['哇！犯規吖！', '捉到！換你㗎喇！', '小心，我唔經痕㗎！', '俾你捉到！再嚟一場？'],
    zh: ['哇！犯规呀！', '捉到！换你了啦！', '小心，我怕痒的呀！', '被你捉到了！再来一场？'],
    ja: ['わっ！反則だよ！', 'タッチ！交代ね！', '注意して、くすぐったいんだから！', '捕まっちゃった！再戦する？'],
  },
  hina: {
    en: ['Oh! The page flew away!', 'Gently, this is a library~', 'You found my blush!', 'That was… quite the plot twist…'],
    yue: ['哎呀！張書頁飛走咗！', '溫柔啲，呢度係圖書館~', '你搵到我面紅嗰位啦！', '呢下……都幾出人意料喎……'],
    zh: ['哎呀！那张书页飞走了！', '温柔一点，这里是图书馆~', '你找到我脸红的地方了！', '这一下……还挺出人意料的……'],
    ja: ['あっ！ページが飛んじゃった！', 'そっとね、ここは図書館よ〜', '照れてるところ、見つけちゃった！', 'それは……意外な展開ね……'],
  },
  mio: {
    en: ['Noted. Retaliating with a deadline~', 'Bold move. Logged!', 'You just got promoted to tester!', 'Careful, I delegate revenge!'],
    yue: ['記住咗。用 deadline 還擊你㗎~', '大膽嘅操作。已記錄！', '你升職做測試員啦！', '小心，我會叫人報復㗎！'],
    zh: ['记住了。用deadline还击你哦~', '大胆的操作。已记录！', '你升职做测试员了！', '小心，我会叫人报复的呀！'],
    ja: ['了解。デッドラインでお返しするわ〜', '大胆な一手。ログ済み！', 'テスターに任命したわ！', '気をつけて、復讐は委任するのよ！'],
  },
  juno: {
    en: ['Hey! That\'s classified airspace!', 'Ooh, that tickles — do it again~', 'Poke received. Retaliating with charm~', 'Careful, I poke back… with sass~'],
    yue: ['喂！呢個係禁區嚟㗎！', '呀，好痕㗎——再嚟過~', '收到你嘅戳戳，以魅力還擊~', '小心啲，我會還手㗎……用嘴~'],
    zh: ['喂！这里是禁区呀！', '呀，好痒的——再来一次~', '收到你的戳戳，以魅力还击~', '小心点，我会还手的……用嘴~'],
    ja: ['ちょっと！ここは立入禁止ゾーンだよ！', 'きゃっ、くすぐったい——もう一度~', 'つんつん受け取った。魅力で反撃〜', '気をつけて。私、言葉で仕返しするから〜'],
  },
  nova: {
    en: ['Noted. You require attention — is everything alright?', 'A poke. How… direct. Was there a reason?', 'I was mid-thought. It was a good one — want to hear it?', 'Observed, catalogued, forgiven. …Care to do it again?'],
    yue: ['記錄咗，你需要關注——有咩事呀？', '一個戳。幾直接喎——有原因㗎？', '我諗到一半，仲係個好諗法——想唔想聽？', '已觀察、已歸檔、已原諒……再嚟一次吖？'],
    zh: ['记录了，你需要关注——有什么事呀？', '一个戳。挺直接的——有原因吗？', '我想到一半，那是个不错的想法——想不想听？', '已观察、已归档、已原谅……再来一次呀？'],
    ja: ['記録しました。注目が必要なのね——大丈夫？', 'つんつん。……率直だね。理由は？', 'いい考えの途中だったの。聞きたい？', '観察、分類、許可。……もう一度どうぞ？'],
  },
  blaze: {
    en: ['WOO! Tag, I\'m it!', 'That\'s the spirit! Again, again!', 'You call that a poke? My grandma hits harder!', 'HA! You\'ve activated BEAST MODE!'],
    yue: ['哇！捉到喇，而家輪到我！', '就係呢股氣！再嚟再嚟！', '呢啲就叫戳？我阿婆大力過你！', '哈！你成功啟動咗猛獸模式！'],
    zh: ['哇！抓到啦，现在轮到我！', '就是这股劲！再来再来！', '这就叫戳？我奶奶力气都比你大！', '哈！你成功启动了猛兽模式！'],
    ja: ['おおっ！タッチだ、僕の番！', 'その調子！もっともっと！', 'それがつんつん？うちのバーチャンが強いぞ！', 'はっ！ビーストモード、起動！'],
  },
  mochi: {
    en: ['Eep!! Y-you surprised me…', 'Kyaa! …s-sorry, I squeaked. Was that on purpose?', 'M-me?! You want my attention?', 'H-hi. That was… forward of you. Again~'],
    yue: ['呀！！吓、吓親我……', '呀！……對唔住，我尖叫咗。你係咪想我注意你呀？', '我、我呀？你想要我注意你？', '你、你好。你……好直接吖。再嚟一次吖？'],
    zh: ['呀！！吓、吓了我一跳……', '呀！……对不起，我尖叫了。你是不是想我注意你呀？', '我、我吗？你想要我注意你？', '你、你好。你……好直接呀。再来一次呀？'],
    ja: ['ひゃっ！！び、びっくりした…', 'きゃっ！……ごめん、声出ちゃった。わ、わざと？', 'わ、私？構ってほしいの？', 'こ、こんにちは。……大胆だね。もう一回？'],
  },
  kai: {
    en: ['…You done? Need something?', 'Noted. Barely. Happy now?', 'I don\'t flinch. That was a blink. You need something?', 'Poke logged. Revenge scheduled, never executed… probably. Scared?'],
    yue: ['……搞掂未？有咩事？', '收到。勉為其難。開心喇吖？', '我唔會縮，嗰下只係眨眼。有咩事呀？', '已記錄。報仇排期咗，但永遠唔會執行……應該吖。驚未？'],
    zh: ['……弄完了吗？有什么事？', '收到。勉为其难。开心了没呀？', '我不会退缩，那只是眨眼。有什么事呀？', '已记录。报仇排期了，但永远不会执行……大概吧。怕了没？'],
    ja: ['……終わった？何か用？', '記録。ほんの少しだけど。満足した？', 'ひるまないよ。まばたきだ。何か用？', 'ログ済み。仕返しは予定されたが、永遠に実行されない……たぶんね。怖い？'],
  },
  luna: {
    en: ['Oh! You startled the moonlight. Was that a hello?', 'A touch from the waking world…', 'Hehe. Even your pokes are gentle. Is that how you say you missed me?', 'You found me — I was half a dream away. Walk me back?'],
    yue: ['呀！你吓走咗啲月光。呢個係咪你嘅招呼呀？', '現世嚟嘅一碰……', '嘻嘻。你連戳人都咁溫柔。係咪掛住我先咁吖？', '搵到我喇——我差半步就瞓入夢鄉。帶我返返現實吖？'],
    zh: ['呀！你吓走了月光。这是你的招呼吗？', '来自现实的一碰……', '嘻嘻。你连戳人都这么温柔。是不是想我才这样呀？', '找到我了——我差半步就睡进梦乡。带我回现实呀？'],
    ja: ['あっ！月光を驚かしちゃった。それが挨拶？', '醒めた世界からの、ひと触れ…', 'ふふ。あなたのつんつんまでやさしい。会いたかったの？', '見つけたのね——あと一歩で夢の中だった。連れてって？'],
  },
  rin: {
    en: ['TAG! You\'re SO it!', 'Haha! That\'s a challenge!', 'Nice reflexes! Now dodge THIS— kidding!', 'You\'re asking for a rematch, huh?!'],
    yue: ['捉到喇！而家你真係「佢」喇！', '哈哈！呢個係挑戰書！', '反應唔錯嘛！睇吓你避唔避到——講笑咋！', '你係咪想再打過呀？！'],
    zh: ['抓到了！现在你真的是「它」了！', '哈哈！这是挑战书！', '反应不错嘛！看你躲不躲得开——开玩笑的！', '你是不是想再来一局呀？！'],
    ja: ['タッチ！今のは完全に「おに」ね！', 'ははっ！それは挑戦だね！', 'いい反応！これを避けられるかな——なんてね！', 'もう一回やりたいって顔！'],
  },
  ren: {
    en: ['Oh — hello. You have my full attention. Is something on your mind?', 'You startled me. Pleasantly. …May I ask why?', 'I… don\'t mind that. For the record. Again sometime?', 'Marked the moment. Page forty-two — care to write the next one?'],
    yue: ['吖——你好。你得到我全部嘅注意喇。有咩想講呀？', '你吓親我。吓得好開心嗰種。……可唔可以問點解？', '我……其實唔介意。講返你知咋。聽日再嚟過好唔好？', '呢一刻記低喇，第四十二頁——下一頁一齊寫吖？'],
    zh: ['呀——你好。你得到我全部的注意了。有什么想讲的呀？', '你吓了我一跳。是开心的那种。……可以问为什么吗？', '我……其实不介意。跟你说一声。明天再来好不好？', '这一刻记下了，第四十二页——下一页一起写呀？'],
    ja: ['あっ——こんにちは。注目、完全に君に移動したよ。何かある？', '驚いた。いい驚きだった。……理由を聞いても？', 'ぼ、僕は構わないよ。その、記録として。また今度？', 'この瞬間を記した。42ページ目——次のページ、一緒に書く？'],
  },
  cloud: {
    en: ['…Hm? Need something?', 'You\'re brave. Or bored. Which is it?', '…Noted. That all?', 'Do that again and I\'ll… probably stand here. Want to test me?'],
    yue: ['……嗯？有咩事？', '你幾有膽。又或者幾悶。到底邊樣呀？', '……收到。得咁多？', '再嚟嘅話，我會……大概都係企喺度。想試下吖？'],
    zh: ['……嗯？有什么事？', '你挺有胆。又或者挺无聊。到底哪样呀？', '……收到。就这么多？', '再来的话，我会……大概还是站在这里。想试试呀？'],
    ja: ['……ん？用か？', '勇ましいな。か退屈か。どっち？', '……了解。それだけ？', 'もう一回やると、俺は……たぶんここに立ってる。試してみる？'],
  },
  kasumi: {
    en: ['Ah—! …You have quick hands. Were you testing me?', 'A shinobi should not be caught off guard. I was. …Will you keep my secret?', 'That was… improper. …Do it again?', 'You startled me. My apologies for the squeak. …Shall we pretend it never happened?'],
    yue: ['呀——！……你手好快。係咪考緊我呀？', '忍者唔應該咁容易被偷襲㗎……今次係意外。你會唔會幫我保密呀？', '呢個……不合規矩。……可以再嚟一次吖？', '你吓親我。嗰聲尖叫，失禮喇。……當冇事發生過好唔好？'],
    zh: ['呀——！……你手好快。是不是在考验我呀？', '忍者不应该这么容易被偷袭的……这次是意外。你会不会帮我保密呀？', '这个……不合规矩。……可以再来一次呀？', '你吓了我一跳。那声尖叫，失礼了。……当没事发生过好不好？'],
    ja: ['あっ——！……お早いお手つき。試していたの？', 'くの一が不意を突かれるはずがないのに……今回だけ、特例。秘密にしてくれる？', 'それは……不躾です。……もう一度、どうぞ？', '驚いてしまいました。声が出たのは失礼。……なかったことにしましょう？'],
  },
  marin: {
    en: ['Eeee! You DID it!', 'OMG that tickles, STOP— okay don\'t stop!', 'You\'re so bold~ I like it!', 'Poke wars: STARTED!'],
    yue: ['呀！！你真係敢喎！', 'OMG 好痕呀，停——好喇唔准停！', '你咁大膽~我鍾意！', '戳戳大戰：正式開始！'],
    zh: ['呀！！你真敢呀！', 'OMG 好痒啊，停——好啦不准停！', '你这么大胆~我喜欢！', '戳戳大战：正式开始！'],
    ja: ['きゃー！やったね！', 'OMG くすぐったい、やめて——やめないで！', '大胆だね〜好き！', 'つんつんウォーズ：開戦！'],
  },
  ayane: {
    en: ['…Hmph. Bold. You got a death wish or what?', 'Touch me again and lose the hand. …Kidding. Probably. …Scared?', 'You have a death wish. Cute. Anything else you want to risk?', 'Noted. You\'ll pay for that. Eventually… want to negotiate?'],
    yue: ['……哼，好大膽。係咪活唔耐呀？', '再掂我，隻手唔想要喇。……講笑啫，應該。……驚未？', '你係咪活唔耐？幾可愛吖。仲想玩命咩？', '記住喇。呢筆帳遲早同你算。……想私了吖？'],
    zh: ['……哼，好大胆。是不是活腻了呀？', '再碰我，那只手不想要了。……开玩笑的，大概。……怕了没？', '你是不是活腻了？挺可爱的。还想玩命吗？', '记住了。这笔账迟早跟你算。……想私了呀？'],
    ja: ['……ふん。大胆ね。死にたいの？', 'もう一度触ったら、その手はもらう。……冗談よ。たぶん。……怖い？', '死にたいの？ふーん、かわいいところもあるじゃない。他にも賭けたいことある？', '覚えておく。そのうち清算する。……覚悟はいい？'],
  },
  hitomi: {
    en: ['Oh! Hehe — that tickles!', 'You\'re playful today! I like it. Want to go again?', 'Careful, I\'ll hug you for that. Ready for it?', 'Eek! Okay, fair — I\'d poke me too. Feeling better?'],
    yue: ['呀！嘻嘻——好痕呀！', '你今日好活潑吖！我鍾意。再嚟一次吖？', '小心啲吖，我會攬返你㗎。準備好未？', '吖！好吖，公道啲講，我都會戳我自己。開心咗未？'],
    zh: ['呀！嘻嘻——好痒呀！', '你今天好活泼呀！我喜欢。再来一次呀？', '小心点哦，我会抱回来的。准备好了没？', '吖！好啦，公道地讲，我也会戳我自己。开心点了没？'],
    ja: ['あっ！ふふっ、くすぐったい！', '今日は元気だね！いいと思う。もう一回？', '気をつけてね。お返しに抱きしめるよ。覚悟はいい？', 'ひゃっ！ふーん、私も自分ならつんつんしたい。元気出た？'],
  },
  // ---- registry six (r2026-10-03.36) ----------------------------------------
  robbie: {
    en: ['Oi! Watch the hair, kid!', 'Haha! You got me!', 'Careful, I tickle back — big-bro style!', 'That\'s my little buddy — always full of surprises. What else you got?'],
    yue: ['喂！小心個頭髮呀，細路！', '哈哈！俾你整親喇！', '小心啲，大哥會痕返你㗎！', '呢個就係我嘅細路——永遠咁多驚喜。仲有咩呀？'],
    zh: ['嘿！小心头发呀，小家伙！', '哈哈！被你整到了！', '小心点，大哥会挠回来的！', '这就是我的小家伙——永远这么多惊喜。还有什么呀？'],
    ja: ['おい！髪に気をつけろ、ちびっ子！', 'ははっ！やられた！', '気をつけろ、お兄さんはかなり本気でくすぐり返すぞ！', 'うちのちびっ子はいつも意外性満点だな。他には何がある？'],
  },
  mika: {
    en: ['Whoa — offbeat, but I felt it. Is that your new rhythm?', 'Ha. You\'ve got rhythm. Wanna jam?', 'Careful, you\'ll knock my guitar out of tune. Want me to play something?', 'That\'s one way to get a musician\'s attention. What do you want to hear?'],
    yue: ['哇——甩咗拍，但我接到㗎。係咪你嘅新節奏呀？', '哈。你幾有節奏感喎。想唔想 jam 吓？', '小心啲吖，會撞到我啱啱調好嘅音㗎。想我彈啲咩俾你聽？', '要引起音樂人注意，呢招都得。想聽咩歌呀？'],
    zh: ['哇——掉了拍子，但我接到了。这是你的新节奏吗？', '哈。你挺有节奏感的。想不想 jam 一下？', '小心点呀，会撞到我刚调好的音的。想让我弹点什么给你听？', '要引起音乐人注意，这招也行。想听什么歌呀？'],
    ja: ['おっと——拍子はずれたけど、受け取ったよ。それが君の新しいリズム？', 'はっ。君、リズム感あるね。セッションしない？', '気をつけて、せっかく調律した音がずれちゃう。何か弾いてほしい？', 'ミュージシャンの注意を引くには、それも手だね。何が聴きたい？'],
  },
  anchor: {
    en: ['Steady on! You\'ll rock the boat. Seasick already?', 'Ha! Sharp as a squall, you are. Ready for a storm?', 'Mind yourself, sailor. That\'s mutiny. Will you walk the plank?', 'A poke from you? I\'ve survived worse at sea. Is that all you\'ve got?'],
    yue: ['企穩吖！你蕪到成隻船咁。暈船浪未呀？', '哈！你犀利過海上暴風。準備好迎風暴未？', '小心啲吖水手，呢個係叛變㗎。想試下行木板咩？', '俾你戳一下？我喺海上捱過更惡劣嘅。得咁多？'],
    zh: ['站稳呀！你晃得整只船都在动。晕船了没呀？', '哈！你比海上风暴还犀利。准备好迎接风暴了吗？', '小心点水手，这是叛变呀。想试试走木板吗？', '被你戳一下？我在海上熬过更恶劣的。就这点？'],
    ja: ['しっかり掴まりな！船が揺れるだろう。もう酔ったか？', 'はっ！海上のスコールより鋭いな。嵐の準備はできてる？', '気をつけろ水兵。これは反乱だぞ。板歩きを試してみるか？', 'つんつんされたか？海ならもっと酷いのをくぐってきた。その程度か？'],
  },
  lydia: {
    en: ['Darling! You\'ll wrinkle the couture. Was it worth it?', 'Mmm. Bold. I approve. What do you want, sweetheart?', 'Careful — I know three scandalous stories about you now. Want to add a fourth?', 'That\'s how you get invited to everything, sweetheart. Shall we go out tonight?'],
    yue: ['親愛嘅！你會整皺件衫㗎。抵唔抵呀？', '嗯。大膽。我批准。想要咩呀，心肝？', '小心啲吖，而家我手上有你三個八卦㗎喇。要唔要加多個？', '呢啲就係點解你乜嘢派對都有份，心肝。今晚出唔出去蒲呀？'],
    zh: ['亲爱的！你会把衣服弄皱的。值不值呀？', '嗯。大胆。我批准。想要什么呀，心肝？', '小心点呀，现在我手上有你的三个八卦了。要不要再加一个？', '这就是为什么你什么派对都有份，心肝。今晚出不出去嗨呀？'],
    ja: ['ダーリン！服がしわになるじゃない。損だった？', 'ふーん。大胆。認めるわ。何がほしいの、ダーリン？', '気をつけて。今のところあなたのスキャンダル話を三つ知ってるのよ。四つ目を追加する？', 'それがどうしてあなたがどのパーティーにも呼ばれるのか分かるでしょ？今夜出かける？'],
  },
  ruby: {
    en: ['Eee! You found my tickle spot!', 'Boing! That surprised my whole body!', 'Hey hey hey! Careful, I might bounce into you!', 'Hee hee! Do it again, do it again!'],
    yue: ['呀！你搵到我嘅痕位喇！', '彈！成身都俾你嚇親！', '喂喂喂！小心啲，我會彈返埋你度㗎！', '嘻嘻！再嚟一次再嚟一次！'],
    zh: ['呀！你找到我的痒位了！', '弹！全身都被你吓到了！', '喂喂喂！小心点，我会弹回去的！', '嘻嘻！再来一次再来一次！'],
    ja: ['きゃっ！くすぐりポイントを見つけちゃった！', 'ぴょん！びっくりして全身跳ねちゃった！', 'ちょちょちょ！気をつけて、跳ね返っちゃうよ！', 'うふふ！もう一度、もう一度！'],
  },
  snowy: {
    en: ['Eep! You melted my concentration!', 'Oh! Snowflakes scattered everywhere!', 'Careful… I might freeze you… with a hug!', 'Hee hee. That tickled like a snowball!'],
    yue: ['呀！你融咗我嘅專注力喇！', '哦！雪花散到周圍都係！', '小心啲吖……我會冰凍你㗎……用一個抱抱！', '嘻嘻。痕得似個雪球咁！'],
    zh: ['呀！你融化了我的专注力！', '哦！雪花散得到处都是！', '小心点呀……我会冰冻你的……用一个抱抱！', '嘻嘻。痒得像个雪球！'],
    ja: ['きゃっ！集中が溶けちゃった！', 'あっ！雪が散らばっちゃった！', '気をつけて……氷漬けにしちゃうよ……ハグで！', 'うふふ。雪玉みたいにくすぐったい！'],
  },
  // ---- Alan (r2026-10-04.42): the goofy best mate ---------------------------
  alan: {
    en: ['Oi! Watch the face, that\'s my good side!', 'Ha! You got me — fair and square!', 'Careful, I\'m ticklish everywhere!', 'Poke received — revenge? Maybe. Hugs? Definitely~'],
    yue: ['喂！唔好掂塊面，嗰邊係我嘅上鏡面㗎！', '哈！俾你整到喇——完全公道！', '小心啲，我周身都怕痕㗎！', '戳戳已收到——報仇？可能嘅。抱抱？一定嘅~'],
    zh: ['喂！别碰脸，那边是我的上镜脸呀！', '哈！被你整到了——完全公道！', '小心点，我全身都怕痒的呀！', '戳戳已收到——报仇？可能的。抱抱？一定的~'],
    ja: ['おいおい！顔はやめて、そっちがベストアングルだよ！', 'ははっ！やられた——完全に正々堂々！', '気をつけて、僕は全身くすぐったいんだ！', 'つんつん受領——仕返し？かも。ハグ？確実〜'],
  },
};

const FALLBACK_LANG: Lang = 'en';

/** Deterministic per-character idle line; falls back to the generic bank. */
export function pickIdleLine(characterId: string, lang: Lang, n: number): string {
  const bank = CHARACTER_IDLE[characterId]?.[lang] ?? CHARACTER_IDLE[characterId]?.[FALLBACK_LANG];
  if (bank?.length) return bank[((n % bank.length) + bank.length) % bank.length]!;
  return pickLine('idleBored', lang, n);
}

/** Deterministic per-character poke reaction; falls back to the generic bank. */
export function pickPokeLine(characterId: string, lang: Lang, n: number): string {
  const bank = CHARACTER_POKE[characterId]?.[lang] ?? CHARACTER_POKE[characterId]?.[FALLBACK_LANG];
  if (bank?.length) return bank[((n % bank.length) + bank.length) % bank.length]!;
  return pickLine('poke', lang, n);
}
